#### High level:
This notebook shows all the inconsistencies of field that were produced with dictionaries (and have `hebrew` in the name) with their respective numeric values for the `markers_hebrew` table.

The specific analysis below is based on data from `2019-11-16_views_and_main_tables` folder from Nov 16, 2019 that can be found here: https://drive.google.com/drive/folders/1StZkyR7KG_cfPpk8xMj5es3HGkIA00C9?usp=sharing 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()
pd.options.display.max_rows = 200
pd.options.display.max_columns = 100

In [3]:
markers_raw = pd.read_csv('../../views_and_main_tables_2019_11/markers_hebrew.csv')
m_all = markers_raw[markers_raw['accident_year'] < 2019]

C:\Users\rkrichev\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (23,90) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
m_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 720541 entries, 0 to 761517
Data columns (total 98 columns):
id                                           720541 non-null int64
provider_and_id                              720541 non-null int64
provider_code                                720541 non-null int64
provider_code_hebrew                         720541 non-null object
file_type_police                             55400 non-null float64
accident_type                                720541 non-null int64
accident_type_hebrew                         720541 non-null object
accident_severity                            720541 non-null int64
accident_severity_hebrew                     720541 non-null object
accident_timestamp                           720541 non-null object
location_accuracy                            720541 non-null int64
location_accuracy_hebrew                     720541 non-null object
road_type                                    720541 non-null int64
road_type_he

### Helper functions

In [77]:
def calc_diff_counts_hebrew(data, feat_name):
    data = data[(data[feat_name].isnull() == False) & (data[feat_name + '_hebrew'].isnull() == False)]
    print(f'Shape of data: {data.shape}')
    return data[feat_name].value_counts().reset_index(drop=True) - \
           data[feat_name + '_hebrew'].value_counts().reset_index(drop=True)

In [152]:
def merge_with_hebrew(data, feat_name):
    nums_df = data[feat_name].value_counts().reset_index()
    nums_df.columns = ['index_' + feat_name, 'count']

    hebrew_df = data[feat_name + '_hebrew'].value_counts().reset_index()
    hebrew_df.columns = ['index_' + feat_name + '_hebrew', 'count']

    return pd.merge(nums_df, hebrew_df, how='outer', on='count')

### road_shape and road_shape_hebrew

In [4]:
# road_shape                                   720541 non-null int64
# road_shape_hebrew                            720538 non-null object
m_all[(m_all['road_shape'].isnull() == False) & (m_all['road_shape_hebrew'].isnull() == True)]

id  provider_and_id  provider_code  \
218018  2008060753      32008060753              3   
225363  2008069185      32008069185              3   
503229  2012052602      32012052602              3   

                        provider_code_hebrew  file_type_police  accident_type  \
218018  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN              3   
225363  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN              3   
503229  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN              3   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
218018   התנגשות חזית באחור                  3                      קלה   
225363   התנגשות חזית באחור                  3                      קלה   
503229   התנגשות חזית באחור                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
218018  2008-04-17 17:30:00                  3                 מרכז דרך   
225363  2008-10-27 19:15:00                  3                 מרכז דרך   
503229  2012-12-03 18:30:00                  1              עיגון מדויק   

        road_type     road_type_hebrew  road_shape road_shape_hebrew  \
218018          4  לא-עירונית לא בצומת           0               NaN   
225363          4  לא-עירונית לא בצומת           0               NaN   
503229          4  לא-עירונית לא בצומת          15               NaN   

        day_type day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
218018         4         יום אחר           51         מרחב השרון         9   
225363         4         יום אחר           51         מרחב השרון         9   
503229         4         יום אחר           52          מרחב שפלה         1   

           one_lane_hebrew  multi_lane multi_lane_hebrew  speed_limit  \
218018  לא ידוע מס מסלולים           0               NaN            0   
225363  לא ידוע מס מסלולים           0               NaN            0   
503229            חד סיטרי           0               NaN            5   

       speed_limit_hebrew  road_intactness road_intactness_hebrew  road_width  \
218018            לא ידוע                0                לא ידוע           0   
225363            לא ידוע                0                לא ידוע           0   
503229            90 קמ"ש                1            אין ליקויים           3   

       road_width_hebrew  road_sign road_sign_hebrew  road_light  \
218018           לא ידוע          5          לא ידוע          11   
225363           לא ידוע          5          לא ידוע           6   
503229     7 עד 10.5 מטר          3        אין ליקוי           3   

       road_light_hebrew  road_control road_control_hebrew  weather  \
218018       יום לא ידוע           NaN                 NaN        9   
225363      לילה לא ידוע           NaN                 NaN        9   
503229   לילה פעלה תאורה           NaN                 NaN        1   

       weather_hebrew  road_surface road_surface_hebrew  road_object  \
218018        לא ידוע             9             לא ידוע            9   
225363        לא ידוע             9             לא ידוע            9   
503229           בהיר             1                 יבש            9   

       road_object_hebrew  object_distance object_distance_hebrew  \
218018            לא ידוע                9                לא ידוע   
225363            לא ידוע                9                לא ידוע   
503229            לא ידוע                9                לא ידוע   

        didnt_cross didnt_cross_hebrew  cross_mode cross_mode_hebrew  \
218018            9            לא ידוע           0               NaN   
225363            9            לא ידוע           0               NaN   
503229            9            לא ידוע           0               NaN   

        cross_location cross_location_hebrew  cross_direction  \
218018               0                   NaN                9   
225363               0                   NaN                9   
503229               0                   NaN

In [5]:
m_all[(m_all['road_shape']==0) & (m_all['accident_year']==2008)]

id  provider_and_id  provider_code  \
218018  2008060753      32008060753              3   
225363  2008069185      32008069185              3   

                        provider_code_hebrew  file_type_police  accident_type  \
218018  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN              3   
225363  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN              3   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
218018   התנגשות חזית באחור                  3                      קלה   
225363   התנגשות חזית באחור                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
218018  2008-04-17 17:30:00                  3                 מרכז דרך   
225363  2008-10-27 19:15:00                  3                 מרכז דרך   

        road_type     road_type_hebrew  road_shape road_shape_hebrew  \
218018          4  לא-עירונית לא בצומת           0               NaN   
225363          4  לא-עירונית לא בצומת           0               NaN   

        day_type day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
218018         4         יום אחר           51         מרחב השרון         9   
225363         4         יום אחר           51         מרחב השרון         9   

           one_lane_hebrew  multi_lane multi_lane_hebrew  speed_limit  \
218018  לא ידוע מס מסלולים           0               NaN            0   
225363  לא ידוע מס מסלולים           0               NaN            0   

       speed_limit_hebrew  road_intactness road_intactness_hebrew  road_width  \
218018            לא ידוע                0                לא ידוע           0   
225363            לא ידוע                0                לא ידוע           0   

       road_width_hebrew  road_sign road_sign_hebrew  road_light  \
218018           לא ידוע          5          לא ידוע          11   
225363           לא ידוע          5          לא ידוע           6   

       road_light_hebrew  road_control road_control_hebrew  weather  \
218018       יום לא ידוע           NaN                 NaN        9   
225363      לילה לא ידוע           NaN                 NaN        9   

       weather_hebrew  road_surface road_surface_hebrew  road_object  \
218018        לא ידוע             9             לא ידוע            9   
225363        לא ידוע             9             לא ידוע            9   

       road_object_hebrew  object_distance object_distance_hebrew  \
218018            לא ידוע                9                לא ידוע   
225363            לא ידוע                9                לא ידוע   

        didnt_cross didnt_cross_hebrew  cross_mode cross_mode_hebrew  \
218018            9            לא ידוע           0               NaN   
225363            9            לא ידוע           0               NaN   

        cross_location cross_location_hebrew  cross_direction  \
218018               0                   NaN                9   
225363               0                   NaN                9   

       cross_direction_hebrew  road1  road2  km  km_raw km_accurate  \
218018                לא ידוע  471.0    0.0 NaN     NaN         NaN   
225363                לא ידוע  471.0    0.0 NaN     NaN         NaN   

        yishuv_symbol yishuv_name  geo_area          geo_area_hebrew  \
218018              0         NaN         1  ישראל ללא יהודה ושומרון   
225363              0         NaN         1  ישראל ללא יהודה ושומרון   

        day_night day_night_hebrew  day_in_week day_in_week_hebrew  \
218018          1              יום            5              חמישי   
225363          5             לילה            2                שני   

        traffic_light traffic_light_hebrew  region region_hebrew  district  \
218018              9              לא ידוע     NaN           NaN        99   
225363              9              לא ידוע     NaN           NaN        99   

       district_hebrew  natural_area natural_area_hebrew  municipal_status  \
218018             NaN       

In [7]:
m_all[m_all['road_shape']==0]

id  provider_and_id  provider_code  \
218018  2008060753      32008060753              3   
225363  2008069185      32008069185              3   

                        provider_code_hebrew  file_type_police  accident_type  \
218018  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN              3   
225363  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN              3   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
218018   התנגשות חזית באחור                  3                      קלה   
225363   התנגשות חזית באחור                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
218018  2008-04-17 17:30:00                  3                 מרכז דרך   
225363  2008-10-27 19:15:00                  3                 מרכז דרך   

        road_type     road_type_hebrew  road_shape road_shape_hebrew  \
218018          4  לא-עירונית לא בצומת           0               NaN   
225363          4  לא-עירונית לא בצומת           0               NaN   

        day_type day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
218018         4         יום אחר           51         מרחב השרון         9   
225363         4         יום אחר           51         מרחב השרון         9   

           one_lane_hebrew  multi_lane multi_lane_hebrew  speed_limit  \
218018  לא ידוע מס מסלולים           0               NaN            0   
225363  לא ידוע מס מסלולים           0               NaN            0   

       speed_limit_hebrew  road_intactness road_intactness_hebrew  road_width  \
218018            לא ידוע                0                לא ידוע           0   
225363            לא ידוע                0                לא ידוע           0   

       road_width_hebrew  road_sign road_sign_hebrew  road_light  \
218018           לא ידוע          5          לא ידוע          11   
225363           לא ידוע          5          לא ידוע           6   

       road_light_hebrew  road_control road_control_hebrew  weather  \
218018       יום לא ידוע           NaN                 NaN        9   
225363      לילה לא ידוע           NaN                 NaN        9   

       weather_hebrew  road_surface road_surface_hebrew  road_object  \
218018        לא ידוע             9             לא ידוע            9   
225363        לא ידוע             9             לא ידוע            9   

       road_object_hebrew  object_distance object_distance_hebrew  \
218018            לא ידוע                9                לא ידוע   
225363            לא ידוע                9                לא ידוע   

        didnt_cross didnt_cross_hebrew  cross_mode cross_mode_hebrew  \
218018            9            לא ידוע           0               NaN   
225363            9            לא ידוע           0               NaN   

        cross_location cross_location_hebrew  cross_direction  \
218018               0                   NaN                9   
225363               0                   NaN                9   

       cross_direction_hebrew  road1  road2  km  km_raw km_accurate  \
218018                לא ידוע  471.0    0.0 NaN     NaN         NaN   
225363                לא ידוע  471.0    0.0 NaN     NaN         NaN   

        yishuv_symbol yishuv_name  geo_area          geo_area_hebrew  \
218018              0         NaN         1  ישראל ללא יהודה ושומרון   
225363              0         NaN         1  ישראל ללא יהודה ושומרון   

        day_night day_night_hebrew  day_in_week day_in_week_hebrew  \
218018          1              יום            5              חמישי   
225363          5             לילה            2                שני   

        traffic_light traffic_light_hebrew  region region_hebrew  district  \
218018              9              לא ידוע     NaN           NaN        99   
225363              9              לא ידוע     NaN           NaN        99   

       district_hebrew  natural_area natural_area_hebrew  municipal_status  \
218018             NaN       

In [6]:
m_all[(m_all['road_shape']==15) & (m_all['accident_year']==2012)]

id  provider_and_id  provider_code  \
503229  2012052602      32012052602              3   

                        provider_code_hebrew  file_type_police  accident_type  \
503229  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN              3   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
503229   התנגשות חזית באחור                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
503229  2012-12-03 18:30:00                  1              עיגון מדויק   

        road_type     road_type_hebrew  road_shape road_shape_hebrew  \
503229          4  לא-עירונית לא בצומת          15               NaN   

        day_type day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
503229         4         יום אחר           52          מרחב שפלה         1   

       one_lane_hebrew  multi_lane multi_lane_hebrew  speed_limit  \
503229        חד סיטרי           0               NaN            5   

       speed_limit_hebrew  road_intactness road_intactness_hebrew  road_width  \
503229            90 קמ"ש                1            אין ליקויים           3   

       road_width_hebrew  road_sign road_sign_hebrew  road_light  \
503229     7 עד 10.5 מטר          3        אין ליקוי           3   

       road_light_hebrew  road_control road_control_hebrew  weather  \
503229   לילה פעלה תאורה           NaN                 NaN        1   

       weather_hebrew  road_surface road_surface_hebrew  road_object  \
503229           בהיר             1                 יבש            9   

       road_object_hebrew  object_distance object_distance_hebrew  \
503229            לא ידוע                9                לא ידוע   

        didnt_cross didnt_cross_hebrew  cross_mode cross_mode_hebrew  \
503229            9            לא ידוע           0               NaN   

        cross_location cross_location_hebrew  cross_direction  \
503229               0                   NaN                9   

       cross_direction_hebrew  road1  road2     km  km_raw km_accurate  \
503229                לא ידוע    5.0    0.0  190.0   190.0           t   

        yishuv_symbol yishuv_name  geo_area          geo_area_hebrew  \
503229              0         NaN         1  ישראל ללא יהודה ושומרון   

        day_night day_night_hebrew  day_in_week day_in_week_hebrew  \
503229          5             לילה            2                שני   

        traffic_light traffic_light_hebrew  region region_hebrew  district  \
503229              9              לא ידוע     NaN           NaN        99   

       district_hebrew  natural_area natural_area_hebrew  municipal_status  \
503229             NaN           NaN                 NaN               NaN   

       municipal_status_hebrew  yishuv_shape yishuv_shape_hebrew  street1  \
503229                     NaN           NaN                 NaN      NaN   

       street1_hebrew  street2 street2_hebrew  house_number  \
503229            NaN      NaN            NaN           NaN   

        non_urban_intersection non_urban_intersection_hebrew  \
503229                     NaN                           NaN   

       non_urban_intersection_by_junction_number  urban_intersection  \
503229                                       NaN                 NaN   

        accident_year  accident_month  accident_day  accident_hour_raw  \
503229           2012              12             3                 75   

       accident_hour_raw_hebrew  accident_hour  accident_minute  \
503229                      NaN             18               30   

                                                     geom  longitude  \
503229  0101000020E61000004CD62616D67E414060719F754C0D...  34.990908   

         latitude         x         y  
503229  32.103896  199295.0  667852.0

In [8]:
m_all[m_all['road_shape']==15]

id  provider_and_id  provider_code  \
503229  2012052602      32012052602              3   

                        provider_code_hebrew  file_type_police  accident_type  \
503229  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN              3   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
503229   התנגשות חזית באחור                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
503229  2012-12-03 18:30:00                  1              עיגון מדויק   

        road_type     road_type_hebrew  road_shape road_shape_hebrew  \
503229          4  לא-עירונית לא בצומת          15               NaN   

        day_type day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
503229         4         יום אחר           52          מרחב שפלה         1   

       one_lane_hebrew  multi_lane multi_lane_hebrew  speed_limit  \
503229        חד סיטרי           0               NaN            5   

       speed_limit_hebrew  road_intactness road_intactness_hebrew  road_width  \
503229            90 קמ"ש                1            אין ליקויים           3   

       road_width_hebrew  road_sign road_sign_hebrew  road_light  \
503229     7 עד 10.5 מטר          3        אין ליקוי           3   

       road_light_hebrew  road_control road_control_hebrew  weather  \
503229   לילה פעלה תאורה           NaN                 NaN        1   

       weather_hebrew  road_surface road_surface_hebrew  road_object  \
503229           בהיר             1                 יבש            9   

       road_object_hebrew  object_distance object_distance_hebrew  \
503229            לא ידוע                9                לא ידוע   

        didnt_cross didnt_cross_hebrew  cross_mode cross_mode_hebrew  \
503229            9            לא ידוע           0               NaN   

        cross_location cross_location_hebrew  cross_direction  \
503229               0                   NaN                9   

       cross_direction_hebrew  road1  road2     km  km_raw km_accurate  \
503229                לא ידוע    5.0    0.0  190.0   190.0           t   

        yishuv_symbol yishuv_name  geo_area          geo_area_hebrew  \
503229              0         NaN         1  ישראל ללא יהודה ושומרון   

        day_night day_night_hebrew  day_in_week day_in_week_hebrew  \
503229          5             לילה            2                שני   

        traffic_light traffic_light_hebrew  region region_hebrew  district  \
503229              9              לא ידוע     NaN           NaN        99   

       district_hebrew  natural_area natural_area_hebrew  municipal_status  \
503229             NaN           NaN                 NaN               NaN   

       municipal_status_hebrew  yishuv_shape yishuv_shape_hebrew  street1  \
503229                     NaN           NaN                 NaN      NaN   

       street1_hebrew  street2 street2_hebrew  house_number  \
503229            NaN      NaN            NaN           NaN   

        non_urban_intersection non_urban_intersection_hebrew  \
503229                     NaN                           NaN   

       non_urban_intersection_by_junction_number  urban_intersection  \
503229                                       NaN                 NaN   

        accident_year  accident_month  accident_day  accident_hour_raw  \
503229           2012              12             3                 75   

       accident_hour_raw_hebrew  accident_hour  accident_minute  \
503229                      NaN             18               30   

                                                     geom  longitude  \
503229  0101000020E61000004CD62616D67E414060719F754C0D...  34.990908   

         latitude         x         y  
503229  32.103896  199295.0  667852.0

**Null Conclusion**: seems that all `road_shape` 0 and 15 don't have translation into `road_shape_hebrew`

**Specific values mistmatch investigations:**

In [17]:
m_all[(m_all['road_shape']!=0) & (m_all['road_shape']!=15)]['road_shape'].value_counts()

9     462341
8     253586
5       2048
4        922
1        361
3        316
6        311
10       206
11       166
2        157
7        124
Name: road_shape, dtype: int64

In [18]:
m_all[(m_all['road_shape']!=0) & (m_all['road_shape']!=15)]['road_shape_hebrew'].value_counts()

אחר                    462341
כביש ישר / צומת        253586
עקום חד                  2048
שיפוע תלול                922
כניסה למחלף               361
מ. חניה / ת. דלק          316
על גשר/ בתוך מנהרה        261
תחנת אוטובוס              206
נתיב תחבורה ציבורית       166
ביציאה ממחלף              157
מפגש מסילת ברזל           124
על גשר מנהרה               50
Name: road_shape_hebrew, dtype: int64

In [78]:
calc_diff_counts_hebrew(m_all[(m_all['road_shape']!=0) & (m_all['road_shape']!=15)], 'road_shape')

Shape of data: (720538, 98)


0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
6     50.0
7      0.0
8      0.0
9      0.0
10     0.0
11     NaN
dtype: float64

In [21]:
m_all[m_all['road_shape_hebrew'] == 'על גשר מנהרה'].describe()

id  provider_and_id  provider_code  file_type_police  \
count  5.000000e+01     5.000000e+01           50.0               0.0   
mean   2.009121e+09     1.200912e+10            1.0               NaN   
std    9.166888e+05     9.166888e+05            0.0               NaN   
min    2.008003e+09     1.200800e+10            1.0               NaN   
25%    2.008072e+09     1.200807e+10            1.0               NaN   
50%    2.009032e+09     1.200903e+10            1.0               NaN   
75%    2.010014e+09     1.201001e+10            1.0               NaN   
max    2.011067e+09     1.201107e+10            1.0               NaN   

       accident_type  accident_severity  location_accuracy  road_type  \
count      50.000000          50.000000          50.000000  50.000000   
mean        5.000000           2.640000           1.820000   2.640000   
std         3.528311           0.631163           0.962353   0.984782   
min         1.000000           1.000000           1.000000   1.000000   
25%         3.000000           2.000000           1.000000   2.000000   
50%         3.000000           3.000000           1.000000   2.000000   
75%         8.000000           3.000000           3.000000   4.000000   
max        15.000000           3.000000           3.000000   4.000000   

       road_shape   day_type  police_unit   one_lane  multi_lane  speed_limit  \
count        50.0  50.000000    50.000000  50.000000   50.000000    50.000000   
mean          6.0   3.860000    23.060000   1.440000    0.680000     2.340000   
std           0.0   0.495284    15.630178   1.197957    1.168288     1.636447   
min           6.0   2.000000    11.000000   0.000000    0.000000     1.000000   
25%           6.0   4.000000    11.000000   0.000000    0.000000     1.000000   
50%           6.0   4.000000    20.000000   1.500000    0.000000     1.000000   
75%           6.0   4.000000    20.000000   2.000000    1.750000     4.000000   
max           6.0   4.000000    61.000000   4.000000    4.000000     5.000000   

       road_intactness  road_width  road_sign  road_light  road_control  \
count        50.000000    50.00000  50.000000   50.000000      8.000000   
mean          1.000000     2.88000   3.100000    2.780000      4.375000   
std           0.349927     0.91785   0.505076    2.418382      2.825269   
min           0.000000     1.00000   1.000000    1.000000      1.000000   
25%           1.000000     2.00000   3.000000    1.000000      2.000000   
50%           1.000000     3.00000   3.000000    2.000000      4.500000   
75%           1.000000     3.00000   3.000000    3.000000      7.000000   
max           3.000000     5.00000   5.000000   11.000000      7.000000   

         weather  road_surface  road_object  object_distance  didnt_cross  \
count  50.000000     50.000000    50.000000          50.0000    50.000000   
mean    1.080000      1.240000     8.180000           7.4200     8.920000   
std     0.274048      1.152814     1.769238           3.0445     0.395897   
min     1.000000      1.000000     4.000000           1.0000     7.000000   
25%     1.000000      1.000000     9.000000           9.0000     9.000000   
50%     1.000000      1.000000     9.000000           9.0000     9.000000   
75%     1.000000      1.000000     9.000000           9.0000     9.000000   
max     2.000000      9.000000     9.000000           9.0000     9.000000   

       cross_mode  cross_location  cross_direction       road1      road2  \
count   50.000000       50.000000        50.000000   20.000000  20.000000   
mean     0.080000        0.220000         8.700000   50.750000   2.200000   
std      0.444467        1.298193         1.488048   96.334874   9.838699   
min      0.000000        0.000000         1.000000    2.000000   0.000000   
25%      0.000000        0.000000         9.000000    4.000000   0.000000   
50%      0.000000        0.000000         9.000000   20.000000   0.000000   
75%      0.000000        0.000000         9.000000   60.000000

In [22]:
m_all[m_all['road_shape_hebrew'] == 'על גשר/ בתוך מנהרה'].describe()

id  provider_and_id  provider_code  file_type_police  \
count  2.610000e+02     2.610000e+02     261.000000         30.000000   
mean   2.014837e+09     1.270449e+10       1.068966          1.200000   
std    2.081276e+06     3.656403e+09       0.365632          0.610257   
min    2.012001e+09     1.201200e+10       1.000000          1.000000   
25%    2.013019e+09     1.201302e+10       1.000000          1.000000   
50%    2.015012e+09     1.201502e+10       1.000000          1.000000   
75%    2.017018e+09     1.201702e+10       1.000000          1.000000   
max    2.018100e+09     3.201806e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy   road_type  \
count     261.000000         261.000000         261.000000  261.000000   
mean        4.505747           2.735632           1.689655    2.662835   
std         3.156947           0.529000           0.927905    0.992916   
min         1.000000           1.000000           1.000000    1.000000   
25%         2.000000           3.000000           1.000000    2.000000   
50%         3.000000           3.000000           1.000000    2.000000   
75%         5.000000           3.000000           3.000000    4.000000   
max        17.000000           3.000000           4.000000    4.000000   

       road_shape    day_type  police_unit    one_lane  multi_lane  \
count       261.0  261.000000   261.000000  261.000000  261.000000   
mean          6.0    3.862069    30.946360    1.111111    1.157088   
std           0.0    0.571888    19.780259    1.446186    1.417690   
min           6.0    1.000000    11.000000    0.000000    0.000000   
25%           6.0    4.000000    11.000000    0.000000    0.000000   
50%           6.0    4.000000    20.000000    1.000000    0.000000   
75%           6.0    4.000000    51.000000    2.000000    2.000000   
max           6.0    4.000000    61.000000    9.000000    5.000000   

       speed_limit  road_intactness  road_width   road_sign  road_light  \
count   261.000000       261.000000  261.000000  261.000000  261.000000   
mean      2.371648         1.003831    2.804598    3.038314    2.333333   
std       1.634896         0.297400    1.093749    0.325912    2.051266   
min       1.000000         0.000000    0.000000    1.000000    1.000000   
25%       1.000000         1.000000    2.000000    3.000000    1.000000   
50%       1.000000         1.000000    3.000000    3.000000    1.000000   
75%       4.000000         1.000000    3.000000    3.000000    3.000000   
max       7.000000         3.000000    5.000000    4.000000   11.000000   

       road_control     weather  road_surface  road_object  object_distance  \
count    136.000000  261.000000    261.000000   261.000000       261.000000   
mean       3.904412    1.210728      1.195402     8.383142         8.000000   
std        2.372305    0.893158      0.874938     1.583188         2.505379   
min        1.000000    1.000000      1.000000     1.000000         1.000000   
25%        2.000000    1.000000      1.000000     9.000000         9.000000   
50%        2.000000    1.000000      1.000000     9.000000         9.000000   
75%        7.000000    1.000000      1.000000     9.000000         9.000000   
max        7.000000    9.000000      9.000000     9.000000         9.000000   

       didnt_cross  cross_mode  cross_location  cross_direction        road1  \
count   261.000000  261.000000      261.000000       261.000000   130.000000   
mean      8.961686    0.076628        0.099617         8.681992   392.215385   
std       0.313889    0.384645        0.478017         1.522404  1329.760024   
min       6.000000    0.000000        0.000000         1.000000     1.000000   
25%       9.000000    0.000000        0.000000         9.000000     4.000000   
50%       9.000000    0.000000        0.000000         9.000000    40.000000   
75%       9.000000    0.000000        0.000000         9.000000    83.500000   
max       9.000000    3.000000   

**Specific values conclusions:**
- Till 2011 (including) `road_shape` 3 was called `על גשר מנהרה` that was later changed to `על גשר/ בתוך מנהרה`

### one_lane and one_lane_hebrew

In [10]:
# one_lane                                     720541 non-null int64
# one_lane_hebrew                              657395 non-null object
m_all[(m_all['one_lane'].isnull() == False) & (m_all['one_lane_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  6.314600e+04     6.314600e+04   63146.000000       4953.000000   
mean   2.012672e+09     1.238197e+10       1.036930          1.022613   
std    3.220278e+06     2.692632e+09       0.269254          0.211478   
min    2.008000e+09     1.200800e+10       1.000000          1.000000   
25%    2.010015e+09     1.201002e+10       1.000000          1.000000   
50%    2.012063e+09     1.201300e+10       1.000000          1.000000   
75%    2.015092e+09     1.201601e+10       1.000000          1.000000   
max    2.018100e+09     3.201810e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy     road_type  \
count   63146.000000       63146.000000       63146.000000  63146.000000   
mean        3.178159           2.859817           1.495265      2.129161   
std         2.894097           0.405151           0.908892      1.103730   
min         1.000000           1.000000           1.000000      1.000000   
25%         2.000000           3.000000           1.000000      1.000000   
50%         2.000000           3.000000           1.000000      2.000000   
75%         3.000000           3.000000           2.000000      3.000000   
max        20.000000           3.000000           9.000000      4.000000   

         road_shape      day_type   police_unit  one_lane    multi_lane  \
count  63146.000000  63146.000000  63146.000000   63146.0  63146.000000   
mean       8.245922      3.879137     32.359421       0.0      2.643097   
std        0.781467      0.510024     18.304831       0.0      0.736754   
min        1.000000      1.000000     11.000000       0.0      1.000000   
25%        8.000000      4.000000     14.000000       0.0      2.000000   
50%        8.000000      4.000000     33.000000       0.0      3.000000   
75%        9.000000      4.000000     51.000000       0.0      3.000000   
max       11.000000      4.000000     61.000000       0.0      5.000000   

        speed_limit  road_intactness    road_width     road_sign  \
count  63146.000000     63146.000000  63146.000000  63146.000000   
mean       2.209182         0.868416      2.825785      3.044358   
std        1.707097         0.374449      1.212679      0.567256   
min        0.000000         0.000000      0.000000      1.000000   
25%        1.000000         1.000000      2.000000      3.000000   
50%        1.000000         1.000000      3.000000      3.000000   
75%        4.000000         1.000000      3.000000      3.000000   
max        8.000000         4.000000      5.000000      5.000000   

         road_light  road_control       weather  road_surface   road_object  \
count  63146.000000  39342.000000  63146.000000  63146.000000  63146.000000   
mean       2.175926      3.323319      1.173756      1.162449      8.634466   
std        1.929704      2.162129      0.980203      0.929502      1.384110   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      2.000000      1.000000      1.000000      9.000000   
50%        1.000000      2.000000      1.000000      1.000000      9.000000   
75%        3.000000      6.000000      1.000000      1.000000      9.000000   
max       11.000000      7.000000      9.000000      9.000000      9.000000   

       object_distance   didnt_cross    cross_mode  cross_location  \
count     63146.000000  63146.000000  63146.000000    63146.000000   
mean          8.472793      8.936750      0.423368        0.452649   
std           1.861980      0.477731      1.109848        1.179556   
min           1.000000      0.000000      0.000000        0.000000   
25%           9.000000      9.000000      0.000000        0.000000   
50%           9.000000      9.000000      0.000000        0.000000   
75%           9.000000      9.000000      0.000000        0.000000   
max           9.000000      9.000000      9.000000        9.000000   

       cross_direction         road1      

In [11]:
m_all[(m_all['one_lane'].isnull() == False) & (m_all['one_lane_hebrew'].isnull() == True)].shape

(63146, 98)

In [13]:
m_all[m_all['one_lane'] == 0].shape

(63146, 98)

**Null Conclusion:** `one_lane` == 0 of all years is missing

**Specific values mistmatch investigations:**

In [79]:
calc_diff_counts_hebrew(m_all[m_all['one_lane'] != 0], 'one_lane')

Shape of data: (657395, 98)


0    0
1    0
2    0
3    0
4    0
dtype: int64

**Specific values conclusion:** no issues

### multi_lane and multi_lane_hebrew

In [14]:
# multi_lane                                   720541 non-null int64
# multi_lane_hebrew                            63177 non-null object
m_all[(m_all['multi_lane'].isnull() == False) & (m_all['multi_lane_hebrew'].isnull() == True)].shape

(657364, 98)

In [15]:
m_all[(m_all['multi_lane'].isnull() == False) & (m_all['multi_lane_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  6.573640e+05     6.573640e+05  657364.000000      50447.000000   
mean   2.012698e+09     2.919538e+10       2.718269          2.708684   
std    3.194208e+06     6.957639e+09       0.695766          0.705533   
min    2.008000e+09     1.200800e+10       1.000000          1.000000   
25%    2.010023e+09     3.200901e+10       3.000000          3.000000   
50%    2.012061e+09     3.201200e+10       3.000000          3.000000   
75%    2.015093e+09     3.201504e+10       3.000000          3.000000   
max    2.018100e+09     3.201810e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy      road_type  \
count  657364.000000      657364.000000      657364.000000  657364.000000   
mean        4.829880           2.976384           2.406463       2.303838   
std         4.116705           0.170989           1.651954       0.840542   
min         1.000000           1.000000           1.000000       1.000000   
25%         3.000000           3.000000           1.000000       2.000000   
50%         3.000000           3.000000           2.000000       2.000000   
75%         5.000000           3.000000           3.000000       2.000000   
max        20.000000           3.000000           9.000000       4.000000   

          road_shape       day_type    police_unit       one_lane  multi_lane  \
count  657364.000000  657364.000000  657364.000000  657364.000000    657364.0   
mean        8.657302       3.896716      30.778050       8.210942         0.0   
std         0.557364       0.466855      17.804513       2.175194         0.0   
min         0.000000       1.000000      11.000000       1.000000         0.0   
25%         8.000000       4.000000      14.000000       9.000000         0.0   
50%         9.000000       4.000000      20.000000       9.000000         0.0   
75%         9.000000       4.000000      51.000000       9.000000         0.0   
max        15.000000       4.000000      61.000000       9.000000         0.0   

         speed_limit  road_intactness     road_width      road_sign  \
count  657364.000000    657364.000000  657364.000000  657364.000000   
mean        0.221895         0.110754       0.296340       4.763510   
std         4.238523         0.335081       0.873804       0.663001   
min         0.000000         0.000000       0.000000       1.000000   
25%         0.000000         0.000000       0.000000       5.000000   
50%         0.000000         0.000000       0.000000       5.000000   
75%         0.000000         0.000000       0.000000       5.000000   
max      3383.000000         4.000000       5.000000       5.000000   

          road_light  road_control        weather   road_surface  \
count  657364.000000  41554.000000  657364.000000  657364.000000   
mean        8.798378      4.446215       8.031570       8.036940   
std         3.302644      2.332783       2.599665       2.589624   
min         1.000000      0.000000       1.000000       1.000000   
25%         6.000000      2.000000       9.000000       9.000000   
50%        11.000000      5.000000       9.000000       9.000000   
75%        11.000000      7.000000       9.000000       9.000000   
max        11.000000      7.000000       9.000000       9.000000   

         road_object  object_distance    didnt_cross     cross_mode  \
count  657364.000000    657364.000000  657364.000000  657364.000000   
mean        8.877794         8.942682       8.966620       0.119251   
std         0.791455        10.023855       0.366774       0.703511   
min         1.000000         1.000000       0.000000       0.000000   
25%         9.000000         9.000000       9.000000       0.000000   
50%         9.000000         9.000000       9.000000       0.000000   
75%         9.000000         9.000000       9.000000       0.000000   
max         9.000000      1462.000000       9.000000       9.000000   

       cross_location  cross_direction    

In [16]:
m_all[m_all['multi_lane'] == 0].shape

(657364, 98)

**Null Conclusion:** `multi_lane` == 0 of all years is missing

**Specific values mistmatch investigations:**

In [80]:
calc_diff_counts_hebrew(m_all[m_all['multi_lane'] != 0], 'multi_lane')

Shape of data: (63177, 98)


0    0
1    0
2    0
3    0
4    0
dtype: int64

**Specific values conclusion:** no issues

### speed_limit and speed_limit_hebrew

In [19]:
# speed_limit                                  720541 non-null int64
# speed_limit_hebrew                           720540 non-null object
m_all[(m_all['speed_limit'].isnull() == False) & (m_all['speed_limit_hebrew'].isnull() == True)]

id  provider_and_id  provider_code  \
670485  2017079392      32017079392              3   

                        provider_code_hebrew  file_type_police  accident_type  \
670485  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN              8   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
670485  התנגשות עם עצם דומם                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
670485  2017-09-02 12:45:00                  1              עיגון מדויק   

        road_type     road_type_hebrew  road_shape road_shape_hebrew  \
670485          4  לא-עירונית לא בצומת           8   כביש ישר / צומת   

        day_type day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
670485         4         יום אחר           38          מרחב לכיש         1   

       one_lane_hebrew  multi_lane multi_lane_hebrew  speed_limit  \
670485        חד סיטרי           0               NaN         3383   

       speed_limit_hebrew  road_intactness road_intactness_hebrew  road_width  \
670485                NaN                1            אין ליקויים           4   

       road_width_hebrew  road_sign road_sign_hebrew  road_light  \
670485    10.5 עד 14 מטר          3        אין ליקוי           1   

       road_light_hebrew  road_control road_control_hebrew  weather  \
670485      אור יום רגיל           NaN                 NaN        1   

       weather_hebrew  road_surface road_surface_hebrew  road_object  \
670485           בהיר             1                 יבש            6   

       road_object_hebrew  object_distance object_distance_hebrew  \
670485    גדר בטיחות לרכב                1                 עד מטר   

        didnt_cross didnt_cross_hebrew  cross_mode cross_mode_hebrew  \
670485            9            לא ידוע           0               NaN   

        cross_location cross_location_hebrew  cross_direction  \
670485               0                   NaN                9   

       cross_direction_hebrew  road1  road2     km  km_raw km_accurate  \
670485                לא ידוע    6.0    0.0  910.0   910.0           t   

        yishuv_symbol yishuv_name  geo_area          geo_area_hebrew  \
670485              0         NaN         1  ישראל ללא יהודה ושומרון   

        day_night day_night_hebrew  day_in_week day_in_week_hebrew  \
670485          1              יום            7                שבת   

        traffic_light traffic_light_hebrew  region region_hebrew  district  \
670485              9              לא ידוע     NaN           NaN        99   

       district_hebrew  natural_area natural_area_hebrew  municipal_status  \
670485             NaN           NaN                 NaN               NaN   

       municipal_status_hebrew  yishuv_shape yishuv_shape_hebrew  street1  \
670485                     NaN           NaN                 NaN      NaN   

       street1_hebrew  street2 street2_hebrew  house_number  \
670485            NaN      NaN            NaN           NaN   

        non_urban_intersection non_urban_intersection_hebrew  \
670485                     NaN                           NaN   

       non_urban_intersection_by_junction_number  urban_intersection  \
670485                                       NaN                 NaN   

        accident_year  accident_month  accident_day  accident_hour_raw  \
670485           2017               9             2                 52   

       accident_hour_raw_hebrew  accident_hour  accident_minute  \
670485              12:45-12:59             12               45   

                                                     geom  longitude  \
670485  0101000020E6100000E6E9282E0D694140CCAE7A7A55B6...  34.820715   

         latitude         x         y  
670485  31.712242  183077.0  624467.0

In [20]:
m_all[(m_all['speed_limit'].isnull() == False) & (m_all['speed_limit_hebrew'].isnull() == True)]['speed_limit']

670485    3383
Name: speed_limit, dtype: int64

In [21]:
m_all['speed_limit'].value_counts()

0       577210
1        96678
4        18629
5        13605
3         6390
2         6338
6          868
7          790
8           32
3383         1
Name: speed_limit, dtype: int64

**Null Conclusion:** Speed limit 3383 has wrong information

**Specific values mistmatch investigations:**

In [81]:
calc_diff_counts_hebrew(m_all[m_all['speed_limit'] != 3383], 'speed_limit')

Shape of data: (720540, 98)


0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

**Specific values conclusion:** no issues

### road_control and road_control_hebrew

In [23]:
# road_control                                 80906 non-null float64
# road_control_hebrew                          80904 non-null object
m_all[(m_all['road_control'].isnull() == False) & (m_all['road_control_hebrew'].isnull() == True)]

id  provider_and_id  provider_code  \
64687   2010060525      12010060525              1   
384308  2010026652      32010026652              3   

                        provider_code_hebrew  file_type_police  accident_type  \
64687   הלשכה המרכזית לסטטיסטיקה - סוג תיק 1               NaN              2   
384308  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN             15   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
64687    התנגשות חזית אל צד                  3                      קלה   
384308                  אחר                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
64687   2010-07-07 18:30:00                  1              עיגון מדויק   
384308  2010-12-02 11:30:00                  1              עיגון מדויק   

        road_type road_type_hebrew  road_shape road_shape_hebrew  day_type  \
64687           1    עירונית בצומת           8   כביש ישר / צומת         4   
384308          1    עירונית בצומת           8   כביש ישר / צומת         4   

       day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
64687          יום אחר           20           מחוז ת"א         1   
384308         יום אחר           20           מחוז ת"א         9   

           one_lane_hebrew  multi_lane multi_lane_hebrew  speed_limit  \
64687             חד סיטרי           0               NaN            1   
384308  לא ידוע מס מסלולים           0               NaN            0   

       speed_limit_hebrew  road_intactness road_intactness_hebrew  road_width  \
64687          עד 50 קמ"ש                1            אין ליקויים           3   
384308            לא ידוע                0                לא ידוע           0   

       road_width_hebrew  road_sign road_sign_hebrew  road_light  \
64687      7 עד 10.5 מטר          3        אין ליקוי           1   
384308           לא ידוע          5          לא ידוע          11   

       road_light_hebrew  road_control road_control_hebrew  weather  \
64687       אור יום רגיל           0.0                 NaN        1   
384308       יום לא ידוע           0.0                 NaN        9   

       weather_hebrew  road_surface road_surface_hebrew  road_object  \
64687            בהיר             1                 יבש            9   
384308        לא ידוע             9             לא ידוע            9   

       road_object_hebrew  object_distance object_distance_hebrew  \
64687             לא ידוע                9                לא ידוע   
384308            לא ידוע                9                לא ידוע   

        didnt_cross didnt_cross_hebrew  cross_mode cross_mode_hebrew  \
64687             9            לא ידוע           0               NaN   
384308            9            לא ידוע           0               NaN   

        cross_location cross_location_hebrew  cross_direction  \
64687                0                   NaN                9   
384308               0                   NaN                9   

       cross_direction_hebrew  road1  road2  km  km_raw km_accurate  \
64687                 לא ידוע    NaN    NaN NaN     NaN         NaN   
384308                לא ידוע    NaN    NaN NaN     NaN         NaN   

        yishuv_symbol   yishuv_name  geo_area          geo_area_hebrew  \
64687            5000  תל אביב -יפו         1  ישראל ללא יהודה ושומרון   
384308           5000  תל אביב -יפו         1  ישראל ללא יהודה ושומרון   

        day_night day_night_hebrew  day_in_week day_in_week_hebrew  \
64687           1              יום            4              רביעי   
384308          1              יום            5              חמישי   

        traffic_light traffic_light_hebrew  region region_hebrew  district  \
64687               9              לא ידוע     5.0       תל אביב        51   
384308              1                   כן     5.0       תל אביב        51   

       district_hebrew  natural_area natural_area_hebrew  municipal_status  \
64687          תל אביב         511.

In [24]:
m_all[m_all['road_control'] == 0]

id  provider_and_id  provider_code  \
64687   2010060525      12010060525              1   
384308  2010026652      32010026652              3   

                        provider_code_hebrew  file_type_police  accident_type  \
64687   הלשכה המרכזית לסטטיסטיקה - סוג תיק 1               NaN              2   
384308  הלשכה המרכזית לסטטיסטיקה - סוג תיק 3               NaN             15   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
64687    התנגשות חזית אל צד                  3                      קלה   
384308                  אחר                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
64687   2010-07-07 18:30:00                  1              עיגון מדויק   
384308  2010-12-02 11:30:00                  1              עיגון מדויק   

        road_type road_type_hebrew  road_shape road_shape_hebrew  day_type  \
64687           1    עירונית בצומת           8   כביש ישר / צומת         4   
384308          1    עירונית בצומת           8   כביש ישר / צומת         4   

       day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
64687          יום אחר           20           מחוז ת"א         1   
384308         יום אחר           20           מחוז ת"א         9   

           one_lane_hebrew  multi_lane multi_lane_hebrew  speed_limit  \
64687             חד סיטרי           0               NaN            1   
384308  לא ידוע מס מסלולים           0               NaN            0   

       speed_limit_hebrew  road_intactness road_intactness_hebrew  road_width  \
64687          עד 50 קמ"ש                1            אין ליקויים           3   
384308            לא ידוע                0                לא ידוע           0   

       road_width_hebrew  road_sign road_sign_hebrew  road_light  \
64687      7 עד 10.5 מטר          3        אין ליקוי           1   
384308           לא ידוע          5          לא ידוע          11   

       road_light_hebrew  road_control road_control_hebrew  weather  \
64687       אור יום רגיל           0.0                 NaN        1   
384308       יום לא ידוע           0.0                 NaN        9   

       weather_hebrew  road_surface road_surface_hebrew  road_object  \
64687            בהיר             1                 יבש            9   
384308        לא ידוע             9             לא ידוע            9   

       road_object_hebrew  object_distance object_distance_hebrew  \
64687             לא ידוע                9                לא ידוע   
384308            לא ידוע                9                לא ידוע   

        didnt_cross didnt_cross_hebrew  cross_mode cross_mode_hebrew  \
64687             9            לא ידוע           0               NaN   
384308            9            לא ידוע           0               NaN   

        cross_location cross_location_hebrew  cross_direction  \
64687                0                   NaN                9   
384308               0                   NaN                9   

       cross_direction_hebrew  road1  road2  km  km_raw km_accurate  \
64687                 לא ידוע    NaN    NaN NaN     NaN         NaN   
384308                לא ידוע    NaN    NaN NaN     NaN         NaN   

        yishuv_symbol   yishuv_name  geo_area          geo_area_hebrew  \
64687            5000  תל אביב -יפו         1  ישראל ללא יהודה ושומרון   
384308           5000  תל אביב -יפו         1  ישראל ללא יהודה ושומרון   

        day_night day_night_hebrew  day_in_week day_in_week_hebrew  \
64687           1              יום            4              רביעי   
384308          1              יום            5              חמישי   

        traffic_light traffic_light_hebrew  region region_hebrew  district  \
64687               9              לא ידוע     5.0       תל אביב        51   
384308              1                   כן     5.0       תל אביב        51   

       district_hebrew  natural_area natural_area_hebrew  municipal_status  \
64687          תל אביב         511.

**Null Conclusion:** `road_control` == 0 of all years is missing, all in year 2010

**Specific values mistmatch investigations:**

In [82]:
calc_diff_counts_hebrew(m_all[(m_all['road_control'] != 0) | (m_all['accident_year'] != 2010)], 'road_control')

Shape of data: (80904, 98)


0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

**Specific values conclusion:** no issues

### object_distance and object_distance_hebrew

In [27]:
# object_distance                              720541 non-null int64
# object_distance_hebrew                       720477 non-null object
m_all[(m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)].shape

(64, 98)

In [28]:
m_all[(m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  6.400000e+01     6.400000e+01           64.0               0.0   
mean   2.011755e+09     3.201176e+10            3.0               NaN   
std    1.324987e+06     1.324987e+06            0.0               NaN   
min    2.010001e+09     3.201000e+10            3.0               NaN   
25%    2.011008e+09     3.201101e+10            3.0               NaN   
50%    2.012003e+09     3.201200e+10            3.0               NaN   
75%    2.013001e+09     3.201300e+10            3.0               NaN   
max    2.014098e+09     3.201410e+10            3.0               NaN   

       accident_type  accident_severity  location_accuracy  road_type  \
count      64.000000               64.0          64.000000  64.000000   
mean        8.046875                3.0           2.203125   2.812500   
std         0.277728                0.0           1.928728   1.005935   
min         8.000000                3.0           1.000000   1.000000   
25%         8.000000                3.0           1.000000   2.000000   
50%         8.000000                3.0           2.000000   2.000000   
75%         8.000000                3.0           3.000000   4.000000   
max        10.000000                3.0           9.000000   4.000000   

       road_shape   day_type  police_unit   one_lane  multi_lane  speed_limit  \
count   64.000000  64.000000    64.000000  64.000000   64.000000    64.000000   
mean     8.859375   3.796875    31.875000   7.953125    0.109375     0.375000   
std      0.559682   0.670931    16.769682   2.651323    0.507630     1.046536   
min      5.000000   1.000000    11.000000   0.000000    0.000000     0.000000   
25%      9.000000   4.000000    12.000000   9.000000    0.000000     0.000000   
50%      9.000000   4.000000    34.000000   9.000000    0.000000     0.000000   
75%      9.000000   4.000000    51.000000   9.000000    0.000000     0.000000   
max      9.000000   4.000000    61.000000   9.000000    3.000000     5.000000   

       road_intactness  road_width  road_sign  road_light  road_control  \
count        64.000000   64.000000  64.000000   64.000000           1.0   
mean          0.093750    0.500000   4.687500    7.437500           6.0   
std           0.293785    1.272418   0.731925    3.284765           NaN   
min           0.000000    0.000000   3.000000    1.000000           6.0   
25%           0.000000    0.000000   5.000000    6.000000           6.0   
50%           0.000000    0.000000   5.000000    6.000000           6.0   
75%           0.000000    0.000000   5.000000   11.000000           6.0   
max           1.000000    5.000000   5.000000   11.000000           6.0   

         weather  road_surface  road_object  object_distance  didnt_cross  \
count  64.000000     64.000000    64.000000        64.000000         64.0   
mean    7.562500      7.515625     5.328125       710.734375          9.0   
std     3.028306      3.116735     2.828734       733.900370          0.0   
min     1.000000      1.000000     1.000000         5.000000          9.0   
25%     9.000000      9.000000     2.000000         5.000000          9.0   
50%     9.000000      9.000000     6.000000         5.000000          9.0   
75%     9.000000      9.000000     8.000000      1462.000000          9.0   
max     9.000000      9.000000     9.000000      1462.000000          9.0   

       cross_mode  cross_location  cross_direction        road1       road2  \
count        64.0            64.0             64.0    27.000000   23.000000   
mean          0.0             0.0              9.0   811.666667   31.391304   
std           0.0             0.0              0.0  1834.927687  150.547407   
min           0.0             0.0              9.0     0.000000    0.000000   
25%           0.0             0.0              9.0    45.000000    0.000000   
50%           0.0             0.0              9.0    75.000000    0.000000   
75%           0.0             0.0              9

In [31]:
m_all[(m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)]['object_distance'].value_counts()

5       33
1462    31
Name: object_distance, dtype: int64

In [29]:
m_all['object_distance'].value_counts()

9       704216
2         7270
1         6489
4         1472
3          825
5          238
1462        31
Name: object_distance, dtype: int64

In [32]:
m_all[(m_all['object_distance']==5) & (m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)].shape

(33, 98)

In [33]:
m_all[(m_all['object_distance']==5) & (m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  3.300000e+01     3.300000e+01           33.0               0.0   
mean   2.012832e+09     3.201283e+10            3.0               NaN   
std    8.657929e+05     8.657929e+05            0.0               NaN   
min    2.012001e+09     3.201200e+10            3.0               NaN   
25%    2.012044e+09     3.201204e+10            3.0               NaN   
50%    2.013001e+09     3.201300e+10            3.0               NaN   
75%    2.014016e+09     3.201402e+10            3.0               NaN   
max    2.014098e+09     3.201410e+10            3.0               NaN   

       accident_type  accident_severity  location_accuracy  road_type  \
count      33.000000               33.0          33.000000  33.000000   
mean        8.060606                3.0           1.575758   2.939394   
std         0.348155                0.0           0.791766   1.058873   
min         8.000000                3.0           1.000000   1.000000   
25%         8.000000                3.0           1.000000   2.000000   
50%         8.000000                3.0           1.000000   2.000000   
75%         8.000000                3.0           2.000000   4.000000   
max        10.000000                3.0           3.000000   4.000000   

       road_shape   day_type  police_unit   one_lane  multi_lane  speed_limit  \
count   33.000000  33.000000    33.000000  33.000000   33.000000    33.000000   
mean     8.878788   3.666667    29.696970   7.636364    0.212121     0.484848   
std      0.331434   0.853913    16.711682   3.008511    0.696311     1.202113   
min      8.000000   1.000000    11.000000   0.000000    0.000000     0.000000   
25%      9.000000   4.000000    12.000000   9.000000    0.000000     0.000000   
50%      9.000000   4.000000    34.000000   9.000000    0.000000     0.000000   
75%      9.000000   4.000000    43.000000   9.000000    0.000000     0.000000   
max      9.000000   4.000000    61.000000   9.000000    3.000000     5.000000   

       road_intactness  road_width  road_sign  road_light  road_control  \
count        33.000000   33.000000  33.000000   33.000000           1.0   
mean          0.181818    0.666667   4.575758    7.000000           6.0   
std           0.391675    1.471960   0.830298    3.436932           NaN   
min           0.000000    0.000000   3.000000    1.000000           6.0   
25%           0.000000    0.000000   5.000000    6.000000           6.0   
50%           0.000000    0.000000   5.000000    6.000000           6.0   
75%           0.000000    0.000000   5.000000   11.000000           6.0   
max           1.000000    5.000000   5.000000   11.000000           6.0   

         weather  road_surface  road_object  object_distance  didnt_cross  \
count  33.000000     33.000000    33.000000             33.0         33.0   
mean    7.333333      7.333333     5.545455              5.0          9.0   
std     3.265986      3.265986     2.682011              0.0          0.0   
min     1.000000      1.000000     1.000000              5.0          9.0   
25%     9.000000      9.000000     5.000000              5.0          9.0   
50%     9.000000      9.000000     6.000000              5.0          9.0   
75%     9.000000      9.000000     8.000000              5.0          9.0   
max     9.000000      9.000000     9.000000              5.0          9.0   

       cross_mode  cross_location  cross_direction        road1  road2  \
count        33.0            33.0             33.0    16.000000   14.0   
mean          0.0             0.0              9.0   442.000000    0.0   
std           0.0             0.0              0.0  1242.537672    0.0   
min           0.0             0.0              9.0     2.000000    0.0   
25%           0.0             0.0              9.0    55.000000    0.0   
50%           0.0             0.0              9.0    70.000000    0.0   
75%           0.0             0.0              9.0   248.750000    0.0   
max      

In [36]:
m_all[(m_all['object_distance']==5) & ((m_all['accident_year'] == 2012) | (m_all['accident_year'] == 2013) | (m_all['accident_year'] == 2014))].shape

(33, 98)

In [34]:
m_all[(m_all['object_distance']==1462) & (m_all['object_distance'].isnull() == False) & (m_all['object_distance_hebrew'].isnull() == True)].shape

(31, 98)

**Null Conclusion:** 
- *all* instances of `object_distance` == 1462
- *all* instances of `object_distance` == 5 during years 2012-2014.  Rest of the years `object_distance` == 5 is OK

**Specific values mistmatch investigations:**

In [83]:
temp = m_all[(m_all['object_distance'] != 1462) & \
             ((m_all['object_distance'] !=5) | \
                  ((m_all['accident_year'] != 2012) & (m_all['accident_year'] != 2013) & (m_all['accident_year'] != 2014)))]
calc_diff_counts_hebrew(temp, 'object_distance')

Shape of data: (720477, 98)


0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

**Specific values conclusion:** no issues

### didnt_cross and didnt_cross_hebrew

In [38]:
# didnt_cross                                  720541 non-null int64
# didnt_cross_hebrew                           720538 non-null object
m_all[(m_all['didnt_cross'].isnull() == False) & (m_all['didnt_cross_hebrew'].isnull() == True)]

id  provider_and_id  provider_code  \
113180  2017035517      12017035517              1   
145608  2015079839      12015079839              1   
150298  2016005012      12016005012              1   

                        provider_code_hebrew  file_type_police  accident_type  \
113180  הלשכה המרכזית לסטטיסטיקה - סוג תיק 1               NaN              4   
145608  הלשכה המרכזית לסטטיסטיקה - סוג תיק 1               NaN              1   
150298  הלשכה המרכזית לסטטיסטיקה - סוג תיק 1               NaN              2   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
113180       התנגשות צד בצד                  3                      קלה   
145608      פגיעה בהולך רגל                  3                      קלה   
150298     התנגשות חזית בצד                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
113180  2017-03-08 20:30:00                  2                מרכז ישוב   
145608  2015-03-02 00:00:00                  1              עיגון מדויק   
150298  2016-06-24 19:00:00                  1              עיגון מדויק   

        road_type  road_type_hebrew  road_shape road_shape_hebrew  day_type  \
113180          2  עירונית לא בצומת           8   כביש ישר / צומת         4   
145608          2  עירונית לא בצומת           8   כביש ישר / צומת         4   
150298          1     עירונית בצומת           9               אחר         4   

       day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
113180         יום אחר           51         מרחב השרון         3   
145608         יום אחר           20           מחוז ת"א         1   
150298         יום אחר           11    מרחב חוף (חיפה)         0   

                   one_lane_hebrew  multi_lane            multi_lane_hebrew  \
113180  דו סיטרי אין קו הפרדה רצוף           0                          NaN   
145608                    חד סיטרי           0                          NaN   
150298                         NaN           3  מיפרדה בנויה ללא גדר בטיחות   

        speed_limit speed_limit_hebrew  road_intactness  \
113180            1         עד 50 קמ"ש                1   
145608            1         עד 50 קמ"ש                4   
150298            1         עד 50 קמ"ש                1   

           road_intactness_hebrew  road_width road_width_hebrew  road_sign  \
113180                אין ליקויים           3     7 עד 10.5 מטר          3   
145608  שוליים גרועים וכביש משובש           1          עד 5 מטר          3   
150298                אין ליקויים           2       5 עד 7  מטר          4   

       road_sign_hebrew  road_light road_light_hebrew  road_control  \
113180        אין ליקוי           6      לילה לא ידוע           6.0   
145608        אין ליקוי           6      לילה לא ידוע           NaN   
150298    לא נדרש תמרור           1      אור יום רגיל           1.0   

       road_control_hebrew  weather weather_hebrew  road_surface  \
113180    תמרור זכות קדימה        1           בהיר             1   
145608                 NaN        1           בהיר             1   
150298            אין בקרה        1           בהיר             1   

       road_surface_hebrew  road_object road_object_hebrew  object_distance  \
113180                 יבש            9            לא ידוע                9   
145608                 יבש            9            לא ידוע                9   
150298                 יבש            9            לא ידוע                9   

       object_distance_hebrew  didnt_cross didnt_cross_hebrew  cross_mode  \
113180                לא ידוע            0                NaN           0   
145608                לא ידוע            0                NaN           3   
150298                לא ידוע            0                NaN           0   

       cross_mode_hebrew  cross_location       cross_location_hebrew  \
113180               NaN               0                         NaN   
145608          חצה רגיל               2  לא במעבר חצייה לא ליד צומת   
150298         

In [39]:
m_all[m_all['didnt_cross'] == 0]

id  provider_and_id  provider_code  \
113180  2017035517      12017035517              1   
145608  2015079839      12015079839              1   
150298  2016005012      12016005012              1   

                        provider_code_hebrew  file_type_police  accident_type  \
113180  הלשכה המרכזית לסטטיסטיקה - סוג תיק 1               NaN              4   
145608  הלשכה המרכזית לסטטיסטיקה - סוג תיק 1               NaN              1   
150298  הלשכה המרכזית לסטטיסטיקה - סוג תיק 1               NaN              2   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
113180       התנגשות צד בצד                  3                      קלה   
145608      פגיעה בהולך רגל                  3                      קלה   
150298     התנגשות חזית בצד                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
113180  2017-03-08 20:30:00                  2                מרכז ישוב   
145608  2015-03-02 00:00:00                  1              עיגון מדויק   
150298  2016-06-24 19:00:00                  1              עיגון מדויק   

        road_type  road_type_hebrew  road_shape road_shape_hebrew  day_type  \
113180          2  עירונית לא בצומת           8   כביש ישר / צומת         4   
145608          2  עירונית לא בצומת           8   כביש ישר / צומת         4   
150298          1     עירונית בצומת           9               אחר         4   

       day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
113180         יום אחר           51         מרחב השרון         3   
145608         יום אחר           20           מחוז ת"א         1   
150298         יום אחר           11    מרחב חוף (חיפה)         0   

                   one_lane_hebrew  multi_lane            multi_lane_hebrew  \
113180  דו סיטרי אין קו הפרדה רצוף           0                          NaN   
145608                    חד סיטרי           0                          NaN   
150298                         NaN           3  מיפרדה בנויה ללא גדר בטיחות   

        speed_limit speed_limit_hebrew  road_intactness  \
113180            1         עד 50 קמ"ש                1   
145608            1         עד 50 קמ"ש                4   
150298            1         עד 50 קמ"ש                1   

           road_intactness_hebrew  road_width road_width_hebrew  road_sign  \
113180                אין ליקויים           3     7 עד 10.5 מטר          3   
145608  שוליים גרועים וכביש משובש           1          עד 5 מטר          3   
150298                אין ליקויים           2       5 עד 7  מטר          4   

       road_sign_hebrew  road_light road_light_hebrew  road_control  \
113180        אין ליקוי           6      לילה לא ידוע           6.0   
145608        אין ליקוי           6      לילה לא ידוע           NaN   
150298    לא נדרש תמרור           1      אור יום רגיל           1.0   

       road_control_hebrew  weather weather_hebrew  road_surface  \
113180    תמרור זכות קדימה        1           בהיר             1   
145608                 NaN        1           בהיר             1   
150298            אין בקרה        1           בהיר             1   

       road_surface_hebrew  road_object road_object_hebrew  object_distance  \
113180                 יבש            9            לא ידוע                9   
145608                 יבש            9            לא ידוע                9   
150298                 יבש            9            לא ידוע                9   

       object_distance_hebrew  didnt_cross didnt_cross_hebrew  cross_mode  \
113180                לא ידוע            0                NaN           0   
145608                לא ידוע            0                NaN           3   
150298                לא ידוע            0                NaN           0   

       cross_mode_hebrew  cross_location       cross_location_hebrew  \
113180               NaN               0                         NaN   
145608          חצה רגיל               2  לא במעבר חצייה לא ליד צומת   
150298         

**Null Conclusion**: all instances of `didnt_cross` == 0 are missing translation

**Specific values mistmatch investigations:**

In [84]:
calc_diff_counts_hebrew(m_all[m_all['didnt_cross'] != 0], 'didnt_cross')

Shape of data: (720538, 98)


0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

**Specific values conclusion:** no issues

### cross_mode and cross_mode_hebrew

In [42]:
# cross_mode                                   720541 non-null int64
# cross_mode_hebrew                            33365 non-null object
m_all[(m_all['cross_mode'].isnull() == False) & (m_all['cross_mode_hebrew'].isnull() == True)].shape

(687176, 98)

In [43]:
m_all[(m_all['cross_mode'].isnull() == False) & (m_all['cross_mode_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  6.871760e+05     6.871760e+05  687176.000000      51999.000000   
mean   2.012661e+09     2.819547e+10       2.618281          2.625262   
std    3.197496e+06     7.859600e+09       0.785958          0.780422   
min    2.008000e+09     1.200800e+10       1.000000          1.000000   
25%    2.010019e+09     3.200805e+10       3.000000          3.000000   
50%    2.012058e+09     3.201104e+10       3.000000          3.000000   
75%    2.015090e+09     3.201502e+10       3.000000          3.000000   
max    2.018100e+09     3.201810e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy      road_type  \
count  687176.000000      687176.000000      687176.000000  687176.000000   
mean        4.860525           2.973969           2.354583       2.314359   
std         4.062755           0.180685           1.642001       0.870384   
min         1.000000           1.000000           1.000000       1.000000   
25%         3.000000           3.000000           1.000000       2.000000   
50%         3.000000           3.000000           2.000000       2.000000   
75%         5.000000           3.000000           3.000000       2.000000   
max        20.000000           3.000000           9.000000       4.000000   

          road_shape       day_type    police_unit       one_lane  \
count  687176.000000  687176.000000  687176.000000  687176.000000   
mean        8.628226       3.894787      30.910289       7.667276   
std         0.585640       0.471854      17.876349       2.968665   
min         0.000000       1.000000      11.000000       0.000000   
25%         8.000000       4.000000      14.000000       9.000000   
50%         9.000000       4.000000      20.000000       9.000000   
75%         9.000000       4.000000      51.000000       9.000000   
max        15.000000       4.000000      61.000000       9.000000   

          multi_lane    speed_limit  road_intactness     road_width  \
count  687176.000000  687176.000000    687176.000000  687176.000000   
mean        0.205259       0.377101         0.155294       0.464478   
std         0.735345       4.212723         0.380841       1.115514   
min         0.000000       0.000000         0.000000       0.000000   
25%         0.000000       0.000000         0.000000       0.000000   
50%         0.000000       0.000000         0.000000       0.000000   
75%         0.000000       0.000000         0.000000       0.000000   
max         5.000000    3383.000000         4.000000       5.000000   

           road_sign     road_light  road_control        weather  \
count  687176.000000  687176.000000  68594.000000  687176.000000   
mean        4.659196       8.398778      3.840788       7.613163   
std         0.775514       3.595113      2.258240       3.016213   
min         1.000000       1.000000      0.000000       1.000000   
25%         5.000000       6.000000      2.000000       9.000000   
50%         5.000000      11.000000      2.000000       9.000000   
75%         5.000000      11.000000      6.000000       9.000000   
max         5.000000      11.000000      7.000000       9.000000   

        road_surface    road_object  object_distance    didnt_cross  \
count  687176.000000  687176.000000    687176.000000  687176.000000   
mean        7.617239       8.850182         8.897560       8.980139   
std         3.009644       0.880553         9.820855       0.279001   
min         1.000000       1.000000         1.000000       0.000000   
25%         9.000000       9.000000         9.000000       9.000000   
50%         9.000000       9.000000         9.000000       9.000000   
75%         9.000000       9.000000         9.000000       9.000000   
max         9.000000       9.000000      1462.000000       9.000000   

          cross_mode  cross_location  cross_direction          road1  \
count  687176.000000   687176.000000    687176.000000  152701.000000   
mean  

In [44]:
m_all[(m_all['cross_mode'].isnull() == False) & (m_all['cross_mode_hebrew'].isnull() == True)]['cross_mode'].value_counts()

0    687175
9         1
Name: cross_mode, dtype: int64

In [46]:
m_all[m_all['cross_mode']==0].shape

(687175, 98)

In [47]:
m_all[m_all['cross_mode']==0]['accident_year'].value_counts()

2008    77228
2009    75924
2010    70608
2011    64368
2012    60632
2015    58648
2013    58504
2016    58240
2017    55642
2014    55382
2018    51999
Name: accident_year, dtype: int64

In [48]:
m_all[m_all['cross_mode']==9].shape

(632, 98)

In [50]:
m_all[(m_all['cross_mode']==9) & (m_all['cross_mode'].isnull() == False) & (m_all['cross_mode_hebrew'].isnull() == True)]

id  provider_and_id  provider_code  \
28780  2008055825      12008055825              1   

                       provider_code_hebrew  file_type_police  accident_type  \
28780  הלשכה המרכזית לסטטיסטיקה - סוג תיק 1               NaN              8   

      accident_type_hebrew  accident_severity accident_severity_hebrew  \
28780  התנגשות עם עצם דומם                  3                      קלה   

        accident_timestamp  location_accuracy location_accuracy_hebrew  \
28780  2008-09-26 16:30:00                  1              עיגון מדויק   

       road_type  road_type_hebrew  road_shape road_shape_hebrew  day_type  \
28780          2  עירונית לא בצומת           9               אחר         4   

      day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
28780         יום אחר           61       מחוז ירושלים         3   

                  one_lane_hebrew  multi_lane multi_lane_hebrew  speed_limit  \
28780  דו סיטרי אין קו הפרדה רצוף           0               NaN            1   

      speed_limit_hebrew  road_intactness road_intactness_hebrew  road_width  \
28780         עד 50 קמ"ש                1            אין ליקויים           3   

      road_width_hebrew  road_sign road_sign_hebrew  road_light  \
28780     7 עד 10.5 מטר          3        אין ליקוי           1   

      road_light_hebrew  road_control road_control_hebrew  weather  \
28780      אור יום רגיל           NaN                 NaN        1   

      weather_hebrew  road_surface road_surface_hebrew  road_object  \
28780           בהיר             1                 יבש            8   

      road_object_hebrew  object_distance object_distance_hebrew  didnt_cross  \
28780                אחר                3               על הכביש            9   

      didnt_cross_hebrew  cross_mode cross_mode_hebrew  cross_location  \
28780            לא ידוע           9               NaN               0   

      cross_location_hebrew  cross_direction cross_direction_hebrew  road1  \
28780                   NaN                9                לא ידוע    NaN   

       road2  km  km_raw km_accurate  yishuv_symbol yishuv_name  geo_area  \
28780    NaN NaN     NaN         NaN           3000     ירושלים         1   

               geo_area_hebrew  day_night day_night_hebrew  day_in_week  \
28780  ישראל ללא יהודה ושומרון          1              יום            6   

      day_in_week_hebrew  traffic_light traffic_light_hebrew  region  \
28780               שישי              9              לא ידוע     1.0   

      region_hebrew  district district_hebrew  natural_area  \
28780       ירושלים        11         ירושלים         111.0   

      natural_area_hebrew  municipal_status municipal_status_hebrew  \
28780           הרי יהודה               0.0                  עירייה   

       yishuv_shape yishuv_shape_hebrew  street1 street1_hebrew  street2  \
28780          11.0             ירושלים   4457.0     עלית הנוער      NaN   

      street2_hebrew  house_number  non_urban_intersection  \
28780            NaN          99.0                     NaN   

      non_urban_intersection_hebrew non_urban_intersection_by_junction_number  \
28780                           NaN                                       NaN   

       urban_intersection  accident_year  accident_month  accident_day  \
28780                 NaN           2008               9            26   

       accident_hour_raw accident_hour_raw_hebrew  accident_hour  \
28780                 67                      NaN             16   

       accident_minute                                               geom  \
28780               30  0101000020E61000003F9FF4C597994140E592A403E6CF...   

       longitude   latitude         x         y  
28780  35.199944  31.812103  219024.0  635476.0

In [51]:
m_all[m_all['cross_mode']==9]['accident_year'].value_counts()

2014    139
2015    127
2016    106
2017    105
2018    103
2013     51
2008      1
Name: accident_year, dtype: int64

**Null Conclusions**:
- All `cross_mode` == 0 that's spread over all years, translation is missing
- `cross_mode` == 9 from year 2008 is problematic (other years are OK)

**Specific values mistmatch investigations:**

In [85]:
temp = m_all[(m_all['cross_mode'] !=0) & ((m_all['cross_mode'] != 9) | (m_all['accident_year'] != 2008))]
calc_diff_counts_hebrew(temp, 'cross_mode')

Shape of data: (33365, 98)


0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

**Specific values conclusion:** no issues

### cross_location and cross_location_hebrew

In [54]:
# cross_location                               720541 non-null int64
# cross_location_hebrew                        28925 non-null object
m_all[(m_all['cross_location'].isnull() == False) & (m_all['cross_location_hebrew'].isnull() == True)].shape

(691616, 98)

In [55]:
m_all[(m_all['cross_location'].isnull() == False) & (m_all['cross_location_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  6.916160e+05     6.916160e+05  691616.000000      52719.000000   
mean   2.012678e+09     2.819009e+10       2.617742          2.622755   
std    3.198464e+06     7.863837e+09       0.786382          0.782425   
min    2.008000e+09     1.200800e+10       1.000000          1.000000   
25%    2.010020e+09     3.200805e+10       3.000000          3.000000   
50%    2.012060e+09     3.201104e+10       3.000000          3.000000   
75%    2.015092e+09     3.201502e+10       3.000000          3.000000   
max    2.018100e+09     3.201810e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy      road_type  \
count  691616.000000      691616.000000      691616.000000  691616.000000   
mean        4.837442           2.973368           2.352876       2.312512   
std         4.062300           0.182743           1.638515       0.868647   
min         1.000000           1.000000           1.000000       1.000000   
25%         3.000000           3.000000           1.000000       2.000000   
50%         3.000000           3.000000           2.000000       2.000000   
75%         5.000000           3.000000           3.000000       2.000000   
max        20.000000           3.000000           9.000000       4.000000   

          road_shape       day_type    police_unit       one_lane  \
count  691616.000000  691616.000000  691616.000000  691616.000000   
mean        8.629557       3.894660      30.909571       7.665365   
std         0.585305       0.472137      17.871505       2.969403   
min         0.000000       1.000000      11.000000       0.000000   
25%         8.000000       4.000000      14.000000       9.000000   
50%         9.000000       4.000000      20.000000       9.000000   
75%         9.000000       4.000000      51.000000       9.000000   
max        15.000000       4.000000      61.000000       9.000000   

          multi_lane    speed_limit  road_intactness     road_width  \
count  691616.000000  691616.000000    691616.000000  691616.000000   
mean        0.204871       0.376525         0.155803       0.464908   
std         0.734868       4.199551         0.381546       1.115532   
min         0.000000       0.000000         0.000000       0.000000   
25%         0.000000       0.000000         0.000000       0.000000   
50%         0.000000       0.000000         0.000000       0.000000   
75%         0.000000       0.000000         0.000000       0.000000   
max         5.000000    3383.000000         4.000000       5.000000   

           road_sign     road_light  road_control        weather  \
count  691616.000000  691616.000000  68915.000000  691616.000000   
mean        4.658655       8.396493      3.847043       7.610323   
std         0.775943       3.597173      2.261135       3.018669   
min         1.000000       1.000000      0.000000       1.000000   
25%         5.000000       6.000000      2.000000       9.000000   
50%         5.000000      11.000000      2.000000       9.000000   
75%         5.000000      11.000000      6.000000       9.000000   
max         5.000000      11.000000      7.000000       9.000000   

        road_surface    road_object  object_distance    didnt_cross  \
count  691616.000000  691616.000000    691616.000000  691616.000000   
mean        7.614681       8.850880         8.897816       8.971033   
std         3.011796       0.878548         9.789427       0.345917   
min         1.000000       1.000000         1.000000       0.000000   
25%         9.000000       9.000000         9.000000       9.000000   
50%         9.000000       9.000000         9.000000       9.000000   
75%         9.000000       9.000000         9.000000       9.000000   
max         9.000000       9.000000      1462.000000       9.000000   

          cross_mode  cross_location  cross_direction          road1  \
count  691616.000000        691616.0    691616.000000  152884.000000   
mean  

In [56]:
m_all[m_all['cross_location']==0].shape

(691616, 98)

**Null Conclusion:** all `cross_location` == 0 spread over numerous years has no translation

**Specific values mistmatch investigations:**

In [86]:
calc_diff_counts_hebrew(m_all[m_all['cross_location'] != 0], 'cross_location')

Shape of data: (28925, 98)


0    0
1    0
2    0
3    0
4    0
dtype: int64

**Specific values conclusion:** no issues

### region and region_hebrew

In [73]:
# region                                       605597 non-null float64
# region_hebrew                                565389 non-null object
m_all[(m_all['region'].isnull() == False) & (m_all['region_hebrew'].isnull() == True)].shape

(40208, 98)

In [74]:
m_all[(m_all['region'].isnull() == False) & (m_all['region_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  4.020800e+04     4.020800e+04        40208.0               0.0   
mean   2.012311e+09     1.201231e+10            1.0               NaN   
std    2.925865e+06     2.925865e+06            0.0               NaN   
min    2.008000e+09     1.200800e+10            1.0               NaN   
25%    2.010007e+09     1.201001e+10            1.0               NaN   
50%    2.012042e+09     1.201204e+10            1.0               NaN   
75%    2.015033e+09     1.201503e+10            1.0               NaN   
max    2.017100e+09     1.201710e+10            1.0               NaN   

       accident_type  accident_severity  location_accuracy     road_type  \
count   40208.000000       40208.000000       40208.000000  40208.000000   
mean        4.080233           2.781785           1.270021      3.664395   
std         3.137877           0.509940           1.067747      0.472207   
min         1.000000           1.000000           1.000000      3.000000   
25%         2.000000           3.000000           1.000000      3.000000   
50%         3.000000           3.000000           1.000000      4.000000   
75%         5.000000           3.000000           1.000000      4.000000   
max        20.000000           3.000000           9.000000      4.000000   

         road_shape      day_type   police_unit      one_lane    multi_lane  \
count  40208.000000  40208.000000  40208.000000  40208.000000  40208.000000   
mean       8.211973      3.868434     29.579163      1.870474      1.139276   
std        1.002749      0.532432     17.346469      2.596545      1.325334   
min        1.000000      1.000000     11.000000      0.000000      0.000000   
25%        8.000000      4.000000     12.000000      0.000000      0.000000   
50%        8.000000      4.000000     20.000000      1.000000      0.000000   
75%        9.000000      4.000000     51.000000      3.000000      2.000000   
max       11.000000      4.000000     61.000000      9.000000      5.000000   

        speed_limit  road_intactness    road_width     road_sign  \
count  40208.000000     40208.000000  40208.000000  40208.000000   
mean       3.582048         0.800960      2.817623      3.241718   
std        1.683188         0.471067      1.326831      0.719973   
min        0.000000         0.000000      0.000000      1.000000   
25%        3.000000         1.000000      2.000000      3.000000   
50%        4.000000         1.000000      3.000000      3.000000   
75%        5.000000         1.000000      4.000000      3.000000   
max        7.000000         4.000000      5.000000      5.000000   

         road_light  road_control       weather  road_surface   road_object  \
count  40208.000000  17413.000000  40208.000000  40208.000000  40208.000000   
mean       2.805884      3.640498      1.754576      1.745026      8.591101   
std        2.717743      2.241423      2.226176      2.208351      1.314634   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      2.000000      1.000000      1.000000      9.000000   
50%        1.000000      2.000000      1.000000      1.000000      9.000000   
75%        3.000000      6.000000      1.000000      1.000000      9.000000   
max       11.000000      7.000000      9.000000      9.000000      9.000000   

       object_distance   didnt_cross    cross_mode  cross_location  \
count     40208.000000  40208.000000  40208.000000    40208.000000   
mean          8.305710      8.970429      0.057725        0.060859   
std           2.111477      0.364566      0.470774        0.474224   
min           1.000000      1.000000      0.000000        0.000000   
25%           9.000000      9.000000      0.000000        0.000000   
50%           9.000000      9.000000      0.000000        0.000000   
75%           9.000000      9.000000      0.000000        0.000000   
max           9.000000      9.000000      9.000000        9.000000   

      

In [75]:
m_all[(m_all['region'] == 9].shape

(44059, 98)

In [101]:
m_all[(m_all['region'] == 9) & (m_all['region_hebrew'].isnull())]['accident_year'].value_counts()

2009    4765
2008    4602
2010    4348
2011    4072
2017    3932
2013    3829
2012    3751
2015    3716
2016    3654
2014    3539
Name: accident_year, dtype: int64

In [102]:
m_all[(m_all['region'] == 9) & (m_all['region_hebrew'].isnull() == False)]['accident_year'].value_counts()

2018    3851
Name: accident_year, dtype: int64

In [107]:
m_all[(m_all['region'] == 9) & (m_all['accident_year'] != 2018)].shape

(40208, 98)

**Null Conclusion:** all `region` == 9 spread over numerous years missing translation, 2018 it was already fixed

**Specific values mistmatch investigations:**

In [109]:
calc_diff_counts_hebrew(m_all[(m_all['region'] != 9) | (m_all['accident_year'] == 2018)], 'region')

Shape of data: (565389, 98)


0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

**Specific values conclusion:** no issues

### district and district_hebrew

In [60]:
# district                                     720541 non-null int64
# district_hebrew                              561538 non-null object
m_all[(m_all['district'].isnull() == False) & (m_all['district_hebrew'].isnull() == True)].shape

(159003, 98)

In [61]:
m_all[(m_all['district'].isnull() == False) & (m_all['district_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  1.590030e+05     1.590030e+05  159003.000000      12902.000000   
mean   2.012632e+09     2.646519e+10       2.445256          2.412804   
std    3.239787e+06     8.953954e+09       0.895406          0.910855   
min    2.008000e+09     1.200800e+10       1.000000          1.000000   
25%    2.010013e+09     1.201709e+10       1.000000          1.000000   
50%    2.012047e+09     3.201005e+10       3.000000          3.000000   
75%    2.015096e+09     3.201407e+10       3.000000          3.000000   
max    2.018100e+09     3.201810e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy      road_type  \
count  159003.000000      159003.000000      159003.000000  159003.000000   
mean        4.592222           2.939001           2.663824       3.773539   
std         3.518502           0.286106           3.069516       0.426166   
min         1.000000           1.000000           1.000000       1.000000   
25%         3.000000           3.000000           1.000000       4.000000   
50%         3.000000           3.000000           1.000000       4.000000   
75%         4.000000           3.000000           3.000000       4.000000   
max        20.000000           3.000000           9.000000       4.000000   

          road_shape       day_type    police_unit       one_lane  \
count  159003.000000  159003.000000  159003.000000  159003.000000   
mean        8.579813       3.891040      31.333660       6.970346   
std         0.692570       0.479733      17.632231       3.499956   
min         0.000000       1.000000      11.000000       0.000000   
25%         8.000000       4.000000      12.000000       3.000000   
50%         9.000000       4.000000      34.000000       9.000000   
75%         9.000000       4.000000      51.000000       9.000000   
max        15.000000       4.000000      61.000000       9.000000   

          multi_lane    speed_limit  road_intactness     road_width  \
count  159003.000000  159003.000000    159003.000000  159003.000000   
mean        0.322491       1.040785         0.229845       0.801450   
std         0.872548       8.681142         0.441579       1.454945   
min         0.000000       0.000000         0.000000       0.000000   
25%         0.000000       0.000000         0.000000       0.000000   
50%         0.000000       0.000000         0.000000       0.000000   
75%         0.000000       1.000000         0.000000       1.000000   
max         5.000000    3383.000000         4.000000       5.000000   

           road_sign     road_light  road_control        weather  \
count  159003.000000  159003.000000  20112.000000  159003.000000   
mean        4.500783       7.676220      3.669799       6.938485   
std         0.879991       3.890408      2.256578       3.477946   
min         1.000000       1.000000      1.000000       1.000000   
25%         4.000000       6.000000      2.000000       2.000000   
50%         5.000000      11.000000      2.000000       9.000000   
75%         5.000000      11.000000      6.000000       9.000000   
max         5.000000      11.000000      7.000000       9.000000   

        road_surface    road_object  object_distance    didnt_cross  \
count  159003.000000  159003.000000    159003.000000  159003.000000   
mean        6.933687       8.783834         8.800230       8.989315   
std         3.479413       0.951210        12.172188       0.217429   
min         1.000000       1.000000         1.000000       1.000000   
25%         2.000000       9.000000         9.000000       9.000000   
50%         9.000000       9.000000         9.000000       9.000000   
75%         9.000000       9.000000         9.000000       9.000000   
max         9.000000       9.000000      1462.000000       9.000000   

          cross_mode  cross_location  cross_direction          road1  \
count  159003.000000   159003.000000    159003.000000  154045.000000   
mean  

In [62]:
m_all[m_all['district']==99].shape

(159003, 98)

**Null Conclusion:** all `district` == 99 spread over numerous years missing translation

**Specific values mistmatch investigations:**

In [110]:
calc_diff_counts_hebrew(m_all[m_all['district'] != 99], 'district')

Shape of data: (561538, 98)


0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
dtype: int64

**Specific values conclusion:** no issues

### natural_area and natural_area_hebrew

In [63]:
# natural_area                                 605597 non-null float64
# natural_area_hebrew                          557164 non-null object
m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].shape

(48433, 98)

In [64]:
m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  4.843300e+04     4.843300e+04   48433.000000       3960.000000   
mean   2.012859e+09     1.296964e+10       1.095679          1.034343   
std    3.139614e+06     4.268719e+09       0.426857          0.259855   
min    2.008000e+09     1.200800e+10       1.000000          1.000000   
25%    2.010042e+09     1.201004e+10       1.000000          1.000000   
50%    2.013023e+09     1.201303e+10       1.000000          1.000000   
75%    2.015093e+09     1.201606e+10       1.000000          1.000000   
max    2.018100e+09     3.201710e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy     road_type  \
count   48433.000000       48433.000000       48433.000000  48433.000000   
mean        4.100820           2.792641           1.328805      3.505213   
std         3.212625           0.496321           1.044801      0.685985   
min         1.000000           1.000000           1.000000      1.000000   
25%         2.000000           3.000000           1.000000      3.000000   
50%         3.000000           3.000000           1.000000      4.000000   
75%         5.000000           3.000000           1.000000      4.000000   
max        20.000000           3.000000           9.000000      4.000000   

         road_shape      day_type   police_unit      one_lane    multi_lane  \
count  48433.000000  48433.000000  48433.000000  48433.000000  48433.000000   
mean       8.255962      3.872050     31.096587      2.221006      1.066442   
std        0.993598      0.524823     17.429198      2.929494      1.315646   
min        1.000000      1.000000     11.000000      0.000000      0.000000   
25%        8.000000      4.000000     12.000000      0.000000      0.000000   
50%        8.000000      4.000000     34.000000      1.000000      0.000000   
75%        9.000000      4.000000     51.000000      3.000000      2.000000   
max       11.000000      4.000000     61.000000      9.000000      5.000000   

        speed_limit  road_intactness    road_width     road_sign  \
count  48433.000000     48433.000000  48433.000000  48433.000000   
mean       3.312452         0.776557      2.669440      3.316520   
std        1.844188         0.486986      1.418832      0.793434   
min        0.000000         0.000000      0.000000      1.000000   
25%        1.000000         1.000000      2.000000      3.000000   
50%        4.000000         1.000000      3.000000      3.000000   
75%        5.000000         1.000000      3.000000      3.000000   
max        8.000000         4.000000      5.000000      5.000000   

         road_light  road_control       weather  road_surface   road_object  \
count  48433.000000  19785.000000  48433.000000  48433.000000  48433.000000   
mean       3.119774      3.687086      2.091363      2.077839      8.602461   
std        3.074494      2.247699      2.657225      2.637163      1.316585   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      2.000000      1.000000      1.000000      9.000000   
50%        1.000000      2.000000      1.000000      1.000000      9.000000   
75%        5.000000      6.000000      1.000000      1.000000      9.000000   
max       11.000000      7.000000      9.000000      9.000000      9.000000   

       object_distance   didnt_cross    cross_mode  cross_location  \
count     48433.000000  48433.000000  48433.000000    48433.000000   
mean          8.340491      8.965788      0.088782        0.085314   
std           2.063355      0.383697      0.587915        0.547570   
min           1.000000      1.000000      0.000000        0.000000   
25%           9.000000      9.000000      0.000000        0.000000   
50%           9.000000      9.000000      0.000000        0.000000   
75%           9.000000      9.000000      0.000000        0.000000   
max           9.000000      9.000000      9.000000        9.000000   

      

In [65]:
m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)]['natural_area'].value_counts()

999.0    44064
432.0     2624
777.0     1744
877.0        1
Name: natural_area, dtype: int64

In [69]:
for area in [999, 432, 777, 877]:
    print(f'{area} shape: {m_all[m_all["natural_area"]==area].shape}')

999 shape: (44064, 98)
432 shape: (8177, 98)
777 shape: (1744, 98)
877 shape: (1, 98)


In [70]:
m_all[(m_all['natural_area']==432) & (m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  2.624000e+03     2.624000e+03    2624.000000               0.0   
mean   2.013528e+09     2.963548e+10       2.762195               NaN   
std    5.075693e+05     6.474725e+09       0.647471               NaN   
min    2.013000e+09     1.201300e+10       1.000000               NaN   
25%    2.013029e+09     3.201302e+10       3.000000               NaN   
50%    2.013060e+09     3.201305e+10       3.000000               NaN   
75%    2.014040e+09     3.201404e+10       3.000000               NaN   
max    2.014100e+09     3.201410e+10       3.000000               NaN   

       accident_type  accident_severity  location_accuracy   road_type  \
count    2624.000000        2624.000000        2624.000000  2624.00000   
mean        4.568216           2.988186           2.205793     1.95122   
std         4.068504           0.127490           0.717111     0.21545   
min         1.000000           1.000000           1.000000     1.00000   
25%         2.000000           3.000000           2.000000     2.00000   
50%         3.000000           3.000000           2.000000     2.00000   
75%         5.000000           3.000000           3.000000     2.00000   
max        20.000000           3.000000           3.000000     2.00000   

        road_shape     day_type  police_unit     one_lane   multi_lane  \
count  2624.000000  2624.000000  2624.000000  2624.000000  2624.000000   
mean      8.919588     3.906631    51.727134     8.194360     0.127287   
std       0.317271     0.443586     2.936916     2.402096     0.601652   
min       5.000000     1.000000    12.000000     0.000000     0.000000   
25%       9.000000     4.000000    52.000000     9.000000     0.000000   
50%       9.000000     4.000000    52.000000     9.000000     0.000000   
75%       9.000000     4.000000    52.000000     9.000000     0.000000   
max       9.000000     4.000000    61.000000     9.000000     5.000000   

       speed_limit  road_intactness   road_width    road_sign   road_light  \
count  2624.000000      2624.000000  2624.000000  2624.000000  2624.000000   
mean      0.124619         0.111280     0.294207     4.777058     8.937881   
std       0.394515         0.350103     0.930459     0.664605     3.220270   
min       0.000000         0.000000     0.000000     1.000000     1.000000   
25%       0.000000         0.000000     0.000000     5.000000     6.000000   
50%       0.000000         0.000000     0.000000     5.000000    11.000000   
75%       0.000000         0.000000     0.000000     5.000000    11.000000   
max       5.000000         4.000000     5.000000     5.000000    11.000000   

       road_control      weather  road_surface  road_object  object_distance  \
count    148.000000  2624.000000   2624.000000  2624.000000      2624.000000   
mean       4.689189     8.108994      8.113186     8.830030         8.928735   
std        2.166069     2.506783      2.499515     1.009334         0.706614   
min        1.000000     1.000000      1.000000     1.000000         1.000000   
25%        2.000000     9.000000      9.000000     9.000000         9.000000   
50%        5.000000     9.000000      9.000000     9.000000         9.000000   
75%        7.000000     9.000000      9.000000     9.000000         9.000000   
max        7.000000     9.000000      9.000000     9.000000         9.000000   

       didnt_cross   cross_mode  cross_location  cross_direction  road1  \
count  2624.000000  2624.000000     2624.000000      2624.000000    0.0   
mean      8.963034     0.135671        0.105564         8.820122    NaN   
std       0.325211     0.749050        0.689709         1.158946    NaN   
min       1.000000     0.000000        0.000000         1.000000    NaN   
25%       9.000000     0.000000        0.000000         9.000000    NaN   
50%       9.000000     0.000000        0.000000         9.000000    NaN   
75%       9.000000     0.000000        0.000000         9.000000    NaN   
m

In [72]:
m_all[(m_all['natural_area']==432) & ((m_all['accident_year']==2013) | (m_all['accident_year']==2014))].shape

(2624, 98)

In [73]:
m_all[m_all['natural_area']==432]['accident_year'].value_counts()

2017    1426
2016    1416
2015    1368
2018    1343
2013    1335
2014    1289
Name: accident_year, dtype: int64

In [74]:
m_all[(m_all['natural_area']==999) & (m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  4.406400e+04     4.406400e+04   44064.000000       3851.000000   
mean   2.012813e+09     1.201508e+10       1.000227          1.032719   
std    3.231181e+06     2.131036e+08       0.021304          0.253740   
min    2.008000e+09     1.200800e+10       1.000000          1.000000   
25%    2.010027e+09     1.201003e+10       1.000000          1.000000   
50%    2.013005e+09     1.201300e+10       1.000000          1.000000   
75%    2.016012e+09     1.201601e+10       1.000000          1.000000   
max    2.018100e+09     3.201710e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy     road_type  \
count   44064.000000       44064.000000       44064.000000  44064.000000   
mean        4.076026           2.780297           1.255015      3.665441   
std         3.129690           0.510028           1.038262      0.472082   
min         1.000000           1.000000           1.000000      2.000000   
25%         2.000000           3.000000           1.000000      3.000000   
50%         3.000000           3.000000           1.000000      4.000000   
75%         5.000000           3.000000           1.000000      4.000000   
max        20.000000           3.000000           9.000000      4.000000   

         road_shape      day_type   police_unit      one_lane    multi_lane  \
count  44064.000000  44064.000000  44064.000000  44064.000000  44064.000000   
mean       8.220293      3.868509     29.429353      1.854802      1.139388   
std        0.997769      0.532027     17.330309      2.570624      1.326881   
min        1.000000      1.000000     11.000000      0.000000      0.000000   
25%        8.000000      4.000000     12.000000      0.000000      0.000000   
50%        8.000000      4.000000     20.000000      1.000000      0.000000   
75%        9.000000      4.000000     51.000000      3.000000      2.000000   
max       11.000000      4.000000     61.000000      9.000000      5.000000   

        speed_limit  road_intactness    road_width     road_sign  \
count  44064.000000     44064.000000  44064.000000  44064.000000   
mean       3.586034         0.811683      2.826752      3.236792   
std        1.685681         0.463431      1.323109      0.713399   
min        0.000000         0.000000      0.000000      1.000000   
25%        3.000000         1.000000      2.000000      3.000000   
50%        4.000000         1.000000      3.000000      3.000000   
75%        5.000000         1.000000      4.000000      3.000000   
max        8.000000         4.000000      5.000000      5.000000   

         road_light  road_control       weather  road_surface   road_object  \
count  44064.000000  19198.000000  44064.000000  44064.000000  44064.000000   
mean       2.797817      3.639754      1.752269      1.734454      8.594590   
std        2.713108      2.238042      2.223584      2.192203      1.309387   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      2.000000      1.000000      1.000000      9.000000   
50%        1.000000      2.000000      1.000000      1.000000      9.000000   
75%        3.000000      6.000000      1.000000      1.000000      9.000000   
max       11.000000      7.000000      9.000000      9.000000      9.000000   

       object_distance   didnt_cross    cross_mode  cross_location  \
count     44064.000000  44064.000000  44064.000000    44064.000000   
mean          8.308347      8.970974      0.060957        0.061479   
std           2.107313      0.360167      0.493341        0.474013   
min           1.000000      1.000000      0.000000        0.000000   
25%           9.000000      9.000000      0.000000        0.000000   
50%           9.000000      9.000000      0.000000        0.000000   
75%           9.000000      9.000000      0.000000        0.000000   
max           9.000000      9.000000      9.000000        9.000000   

      

In [75]:
m_all[(m_all['natural_area']==777) & (m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  1.744000e+03     1.744000e+03         1744.0        109.000000   
mean   2.013027e+09     1.201303e+10            1.0          1.091743   
std    2.967755e+06     2.967755e+06            0.0          0.420346   
min    2.008000e+09     1.200800e+10            1.0          1.000000   
25%    2.011004e+09     1.201100e+10            1.0          1.000000   
50%    2.013040e+09     1.201304e+10            1.0          1.000000   
75%    2.015081e+09     1.201508e+10            1.0          1.000000   
max    2.018099e+09     1.201810e+10            1.0          3.000000   

       accident_type  accident_severity  location_accuracy    road_type  \
count    1744.000000        1744.000000        1744.000000  1744.000000   
mean        4.024656           2.810206           1.869266     1.795872   
std         3.729212           0.427254           0.827730     0.403179   
min         1.000000           1.000000           1.000000     1.000000   
25%         1.000000           3.000000           1.000000     2.000000   
50%         2.000000           3.000000           2.000000     2.000000   
75%         7.000000           3.000000           3.000000     2.000000   
max        19.000000           3.000000           3.000000     2.000000   

       road_shape     day_type  police_unit     one_lane   multi_lane  \
count  1744.00000  1744.000000  1744.000000  1744.000000  1744.000000   
mean      8.15883     3.909404    42.191514     2.485665     0.637041   
std       1.18680     0.445340     0.981771     2.355843     1.181529   
min       3.00000     1.000000    41.000000     0.000000     0.000000   
25%       8.00000     4.000000    41.000000     1.000000     0.000000   
50%       8.00000     4.000000    43.000000     3.000000     0.000000   
75%       9.00000     4.000000    43.000000     3.000000     0.000000   
max      10.00000     4.000000    43.000000     9.000000     5.000000   

       speed_limit  road_intactness   road_width    road_sign   road_light  \
count  1744.000000      1744.000000  1744.000000  1744.000000  1744.000000   
mean      1.197821         0.889908     2.268349     3.133601     2.501720   
std       0.875743         0.515320     1.048019     0.745948     2.645209   
min       0.000000         0.000000     0.000000     1.000000     1.000000   
25%       1.000000         1.000000     2.000000     3.000000     1.000000   
50%       1.000000         1.000000     2.000000     3.000000     1.000000   
75%       1.000000         1.000000     3.000000     3.000000     3.000000   
max       7.000000         4.000000     5.000000     5.000000    11.000000   

       road_control      weather  road_surface  road_object  object_distance  \
count    439.000000  1744.000000   1744.000000  1744.000000      1744.000000   
mean       5.419134     1.605505      1.673739     8.458716         8.267202   
std        1.910604     2.022051      2.091065     1.785874         2.175528   
min        1.000000     1.000000      1.000000     1.000000         1.000000   
25%        5.000000     1.000000      1.000000     9.000000         9.000000   
50%        6.000000     1.000000      1.000000     9.000000         9.000000   
75%        7.000000     1.000000      1.000000     9.000000         9.000000   
max        7.000000     9.000000      9.000000     9.000000         9.000000   

       didnt_cross   cross_mode  cross_location  cross_direction  road1  \
count  1744.000000  1744.000000     1744.000000      1744.000000    0.0   
mean      8.838876     0.721330        0.657110         7.313647    NaN   
std       0.797200     1.477808        1.262221         3.151868    NaN   
min       1.000000     0.000000        0.000000         1.000000    NaN   
25%       9.000000     0.000000        0.000000         9.000000    NaN   
50%       9.000000     0.000000        0.000000         9.000000    NaN   
75%       9.000000     1.000000        0.000000         9.000000    NaN   
m

In [77]:
m_all[(m_all['natural_area']==877) & (m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == True)]

id  provider_and_id  provider_code  \
759812  2017005348      12017005348              1   

                        provider_code_hebrew  file_type_police  accident_type  \
759812  הלשכה המרכזית לסטטיסטיקה - סוג תיק 1               NaN              3   

       accident_type_hebrew  accident_severity accident_severity_hebrew  \
759812   התנגשות חזית באחור                  3                      קלה   

         accident_timestamp  location_accuracy location_accuracy_hebrew  \
759812  2017-04-05 17:00:00                  9                  לא עוגן   

        road_type  road_type_hebrew  road_shape road_shape_hebrew  day_type  \
759812          2  עירונית לא בצומת           8   כביש ישר / צומת         4   

       day_type_hebrew  police_unit police_unit_hebrew  one_lane  \
759812         יום אחר           12          מרחב גליל         3   

                   one_lane_hebrew  multi_lane multi_lane_hebrew  speed_limit  \
759812  דו סיטרי אין קו הפרדה רצוף           0               NaN            1   

       speed_limit_hebrew  road_intactness road_intactness_hebrew  road_width  \
759812         עד 50 קמ"ש                1            אין ליקויים           3   

       road_width_hebrew  road_sign road_sign_hebrew  road_light  \
759812     7 עד 10.5 מטר          3        אין ליקוי           1   

       road_light_hebrew  road_control road_control_hebrew  weather  \
759812      אור יום רגיל           NaN                 NaN        1   

       weather_hebrew  road_surface road_surface_hebrew  road_object  \
759812           בהיר             1                 יבש            9   

       road_object_hebrew  object_distance object_distance_hebrew  \
759812            לא ידוע                9                לא ידוע   

        didnt_cross didnt_cross_hebrew  cross_mode cross_mode_hebrew  \
759812            9            לא ידוע           0               NaN   

        cross_location cross_location_hebrew  cross_direction  \
759812               0                   NaN                9   

       cross_direction_hebrew  road1  road2  km  km_raw km_accurate  \
759812                לא ידוע    NaN    NaN NaN     NaN         NaN   

        yishuv_symbol yishuv_name  geo_area          geo_area_hebrew  \
759812           5301         NaN         1  ישראל ללא יהודה ושומרון   

        day_night day_night_hebrew  day_in_week day_in_week_hebrew  \
759812          1              יום            4              רביעי   

        traffic_light traffic_light_hebrew  region region_hebrew  district  \
759812              9              לא ידוע     8.0       חבל עזה        87   

       district_hebrew  natural_area natural_area_hebrew  municipal_status  \
759812      דיר אל-בלח         877.0                 NaN               NaN   

       municipal_status_hebrew  yishuv_shape    yishuv_shape_hebrew  street1  \
759812                     NaN           9.0  מחנות פליטים עירוניים      NaN   

       street1_hebrew  street2 street2_hebrew  house_number  \
759812            NaN      NaN            NaN        9999.0   

        non_urban_intersection non_urban_intersection_hebrew  \
759812                     NaN                           NaN   

       non_urban_intersection_by_junction_number  urban_intersection  \
759812                                       NaN                 NaN   

        accident_year  accident_month  accident_day  accident_hour_raw  \
759812           2017               4             5                 69   

       accident_hour_raw_hebrew  accident_hour  accident_minute geom  \
759812              17:00-17:14             17                0  NaN   

        longitude  latitude   x   y  
759812        NaN       NaN NaN NaN

**Null Conclusion:** Following `natural_area` had translation issues:
- 999 - all values missing, spread over various years
- 777 - all values missing, spread over various years
- 877 - all values (it's actually 1 value in 2017).  
- 432 - years 2013, 2014 are problematic, rest of the years are OK

**Specific values mistmatch investigations:**

In [153]:
temp = m_all[(m_all['natural_area'].isnull() == False) & (m_all['natural_area_hebrew'].isnull() == False)]
calc_diff_counts_hebrew(temp, 'natural_area')

Shape of data: (557164, 98)


0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
5        0.0
6        0.0
7        0.0
8        0.0
9        0.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       0.0
16    1421.0
17       0.0
18       0.0
19       0.0
20       0.0
21       0.0
22       0.0
23       0.0
24       0.0
25       0.0
26       0.0
27       0.0
28       0.0
29       0.0
30       0.0
31       0.0
32       0.0
33       0.0
34       0.0
35       0.0
36     -35.0
37     -54.0
38    -130.0
39     -96.0
40     -11.0
41     -80.0
42    -116.0
43    -244.0
44      -6.0
45    -303.0
46     -21.0
47      -9.0
48      -3.0
49     -13.0
50     -50.0
51     -52.0
52     -18.0
53     -16.0
54     -57.0
55     -18.0
56      -4.0
57     -79.0
58       NaN
dtype: float64

In [155]:
merge_with_hebrew(temp, 'natural_area')

index_natural_area  count index_natural_area_hebrew
0                511.0  84328              אזור תל אביב
1                311.0  53832                 אזור חיפה
2                111.0  51504                 הרי יהודה
3                512.0  33932               אזור רמת גן
4                422.0  29542            אזור פתח תקווה
5                513.0  27111                אזור חולון
6                623.0  22099              אזור באר שבע
7                442.0  22017          אזור ראשון לציון
8                237.0  20700            הרי נצרת-תירען
9                411.0  18323                מערב השרון
10               421.0  16252                דרום השרון
11               441.0  15355               אזור רחובות
12               324.0  14653                 אזור חדרה
13               613.0  14595                אזור אשדוד
14               614.0  13617               אזור אשקלון
15               241.0  13151                אזור שפרעם
16               431.0  11513                       NaN
17               245.0   7607               אזור נהרייה
18               242.0   7522               אזור כרמיאל
19               234.0   7133                עמק יזרעאל
20               323.0   7114                הר אלכסנדר
21               246.0   6689                  אזור עכו
22               412.0   6501                מזרח השרון
23               221.0   5573                    כינרות
24               432.0   5553                 אזור רמלה
25               243.0   4609                אזור יחיעם
26               625.0   3938                אזור הערבה
27               612.0   3218                 אזור לכיש
28               112.0   2778                שפלת יהודה
29               212.0   2572          גליל עליון מזרחי
30               222.0   2520          גליל תחתון מזרחי
31               611.0   2200                אזור מלאכי
32               235.0   2023                אזור יקנעם
33               621.0   1899                  אזור גרר
34               211.0   1747                  עמק חולה
35               760.0   1426               נפת בית לחם
36               626.0   1386            הר הנגב הצפוני
37               740.0   1332               נפת ראמאללה
38               231.0   1202               עמק בית שאן
39               730.0   1106               נפת טול כרם
40               622.0   1095                 אזור בשור
41               213.0   1015                 אזור חצור
42               322.0    899           אזור זכרון יעקב
43               321.0    655                 חוף הכרמל
44               244.0    649                אזור אילון
45               232.0    346                  עמק חרוד
46               291.0    325               אזור החרמון
47               233.0    316                  רמת כוכב
48               292.0    313                גולן צפוני
49               710.0    300                  נפת גנין
50               293.0    250               גולן תיכוני
51               770.0    198                 נפת חברון
52               236.0    180                  רמת מנשה
53               720.0    164                   נפת שכם
54               750.0    107          נפת ירדן (יריחו)
55               294.0     89                גולן דרומי
56               624.0     85              אזור ים המלח
57               627.0      6            הר הנגב הדרומי
58                 NaN  10092                  אזור לוד
59                 NaN   1421              אזור מודיעין

In [137]:
temp[temp['natural_area_hebrew'] == 'אזור לוד'].shape

(10092, 98)

In [138]:
temp[temp['natural_area'] == 431].shape

(11513, 98)

In [139]:
temp[temp['natural_area'] == 431].shape[0] - temp[temp['natural_area_hebrew'] == 'אזור לוד'].shape[0]

1421

In [140]:
temp[temp['natural_area_hebrew'] == 'אזור מודיעין'].describe()

id  provider_and_id  provider_code  file_type_police  \
count  1.421000e+03     1.421000e+03    1421.000000        371.000000   
mean   2.016597e+09     2.955354e+10       2.753695          2.735849   
std    1.110252e+06     6.574554e+09       0.657456          0.678060   
min    2.015000e+09     1.201501e+10       1.000000          1.000000   
25%    2.016006e+09     3.201506e+10       3.000000          3.000000   
50%    2.017007e+09     3.201608e+10       3.000000          3.000000   
75%    2.018005e+09     3.201709e+10       3.000000          3.000000   
max    2.018100e+09     3.201810e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy    road_type  \
count    1421.000000        1421.000000        1421.000000  1421.000000   
mean        4.341309           2.990148           2.059817     1.813512   
std         3.854709           0.105690           0.899106     0.389637   
min         1.000000           1.000000           1.000000     1.000000   
25%         2.000000           3.000000           1.000000     2.000000   
50%         3.000000           3.000000           2.000000     2.000000   
75%         4.000000           3.000000           3.000000     2.000000   
max        20.000000           3.000000           3.000000     2.000000   

        road_shape     day_type  police_unit     one_lane   multi_lane  \
count  1421.000000  1421.000000  1421.000000  1421.000000  1421.000000   
mean      8.919775     3.919071    51.918367     8.093596     0.172414   
std       0.296522     0.398671     1.785412     2.563634     0.702490   
min       4.000000     1.000000    20.000000     0.000000     0.000000   
25%       9.000000     4.000000    52.000000     9.000000     0.000000   
50%       9.000000     4.000000    52.000000     9.000000     0.000000   
75%       9.000000     4.000000    52.000000     9.000000     0.000000   
max       9.000000     4.000000    61.000000     9.000000     5.000000   

       speed_limit  road_intactness   road_width    road_sign   road_light  \
count  1421.000000      1421.000000  1421.000000  1421.000000  1421.000000   
mean      0.159043         0.113300     0.339901     4.780436     8.909219   
std       0.529454         0.330129     1.003103     0.624328     3.260658   
min       0.000000         0.000000     0.000000     1.000000     1.000000   
25%       0.000000         0.000000     0.000000     5.000000     6.000000   
50%       0.000000         0.000000     0.000000     5.000000    11.000000   
75%       0.000000         0.000000     0.000000     5.000000    11.000000   
max       5.000000         3.000000     5.000000     5.000000    11.000000   

       road_control      weather  road_surface  road_object  object_distance  \
count    133.000000  1421.000000   1421.000000  1421.000000      1421.000000   
mean       4.315789     8.114004      8.096411     8.852217         8.853624   
std        2.023979     2.500075      2.524220     0.940095         1.022822   
min        1.000000     1.000000      1.000000     1.000000         1.000000   
25%        2.000000     9.000000      9.000000     9.000000         9.000000   
50%        5.000000     9.000000      9.000000     9.000000         9.000000   
75%        6.000000     9.000000      9.000000     9.000000         9.000000   
max        7.000000     9.000000      9.000000     9.000000         9.000000   

       didnt_cross   cross_mode  cross_location  cross_direction  road1  \
count  1421.000000  1421.000000     1421.000000      1421.000000    0.0   
mean      8.994370     0.094300        0.075299         8.860662    NaN   
std       0.167742     0.611719        0.534014         1.023117    NaN   
min       3.000000     0.000000        0.000000         1.000000    NaN   
25%       9.000000     0.000000        0.000000         9.000000    NaN   
50%       9.000000     0.000000        0.000000         9.000000    NaN   
75%       9.000000     0.000000        0.000000         9.000000   

In [141]:
temp[temp['natural_area_hebrew'] == 'אזור לוד'].describe()

id  provider_and_id  provider_code  file_type_police  \
count  1.009200e+04     1.009200e+04   10092.000000               0.0   
mean   2.010293e+09     2.827070e+10       2.626040               NaN   
std    1.626658e+06     7.798335e+09       0.779829               NaN   
min    2.008000e+09     1.200800e+10       1.000000               NaN   
25%    2.009027e+09     3.200803e+10       3.000000               NaN   
50%    2.010049e+09     3.201001e+10       3.000000               NaN   
75%    2.011067e+09     3.201105e+10       3.000000               NaN   
max    2.014100e+09     3.201410e+10       3.000000               NaN   

       accident_type  accident_severity  location_accuracy     road_type  \
count   10092.000000       10092.000000       10092.000000  10092.000000   
mean        4.462446           2.988506           2.162901      1.894174   
std         4.146184           0.123000           0.798261      0.307631   
min         1.000000           1.000000           1.000000      1.000000   
25%         2.000000           3.000000           1.000000      2.000000   
50%         3.000000           3.000000           2.000000      2.000000   
75%         4.000000           3.000000           3.000000      2.000000   
max        20.000000           3.000000           3.000000      2.000000   

         road_shape      day_type   police_unit      one_lane    multi_lane  \
count  10092.000000  10092.000000  10092.000000  10092.000000  10092.000000   
mean       8.791815      3.901011     51.758918      8.155470      0.133274   
std        0.461758      0.460092      1.721418      2.437995      0.627054   
min        1.000000      1.000000     11.000000      0.000000      0.000000   
25%        9.000000      4.000000     52.000000      9.000000      0.000000   
50%        9.000000      4.000000     52.000000      9.000000      0.000000   
75%        9.000000      4.000000     52.000000      9.000000      0.000000   
max       10.000000      4.000000     61.000000      9.000000      5.000000   

        speed_limit  road_intactness    road_width     road_sign  \
count  10092.000000     10092.000000  10092.000000  10092.000000   
mean       0.138030         0.047166      0.283987      4.794491   
std        0.438546         0.234636      0.875915      0.623887   
min        0.000000         0.000000      0.000000      1.000000   
25%        0.000000         0.000000      0.000000      5.000000   
50%        0.000000         0.000000      0.000000      5.000000   
75%        0.000000         0.000000      0.000000      5.000000   
max        5.000000         4.000000      5.000000      5.000000   

         road_light  road_control       weather  road_surface   road_object  \
count  10092.000000    682.000000  10092.000000  10092.000000  10092.000000   
mean       8.782699      4.906158      8.040924      8.056778      8.831847   
std        3.299391      2.062886      2.586414      2.564759      0.989672   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        6.000000      2.000000      9.000000      9.000000      9.000000   
50%       11.000000      6.000000      9.000000      9.000000      9.000000   
75%       11.000000      7.000000      9.000000      9.000000      9.000000   
max       11.000000      7.000000      9.000000      9.000000      9.000000   

       object_distance   didnt_cross    cross_mode  cross_location  \
count     10092.000000  10092.000000  10092.000000    10092.000000   
mean          9.166072      8.951050      0.126338        0.144669   
std          20.476674      0.388342      0.651407        0.946010   
min           1.000000      1.000000      0.000000        0.000000   
25%           9.000000      9.000000      0.000000        0.000000   
50%           9.000000      9.000000      0.000000        0.000000   
75%           9.000000      9.000000      0.000000        0.000000   
max        1462.000000      9.000000      9.000000        9.000000   

      

**Specific values conclusion:**

Seems that `natural_area` 431 was called `אזור לוד` until and including 2014, and `אזור מודיעין` since 

### municipal_status and municipal_status_hebrew

In [78]:
# municipal_status                             604357 non-null float64
# municipal_status_hebrew                      604314 non-null object
m_all[(m_all['municipal_status'].isnull() == False) & (m_all['municipal_status_hebrew'].isnull() == True)].shape

(43, 98)

In [79]:
m_all[(m_all['municipal_status'].isnull() == False) & (m_all['municipal_status_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  4.300000e+01     4.300000e+01           43.0               0.0   
mean   2.009058e+09     1.200906e+10            1.0               NaN   
std    1.140631e+06     1.140631e+06            0.0               NaN   
min    2.008004e+09     1.200800e+10            1.0               NaN   
25%    2.008043e+09     1.200804e+10            1.0               NaN   
50%    2.009030e+09     1.200903e+10            1.0               NaN   
75%    2.010008e+09     1.201001e+10            1.0               NaN   
max    2.012055e+09     1.201205e+10            1.0               NaN   

       accident_type  accident_severity  location_accuracy  road_type  \
count      43.000000          43.000000               43.0  43.000000   
mean        6.860465           2.581395                9.0   1.418605   
std         4.857892           0.499169                0.0   0.499169   
min         1.000000           2.000000                9.0   1.000000   
25%         2.000000           2.000000                9.0   1.000000   
50%         8.000000           3.000000                9.0   1.000000   
75%        10.000000           3.000000                9.0   2.000000   
max        15.000000           3.000000                9.0   2.000000   

       road_shape   day_type  police_unit   one_lane  multi_lane  speed_limit  \
count   43.000000  43.000000    43.000000  43.000000   43.000000    43.000000   
mean     8.162791   3.930233    27.720930   3.209302    0.651163     1.720930   
std      1.089566   0.457496    12.251969   2.605472    1.541238     1.548049   
min      3.000000   1.000000    11.000000   0.000000    0.000000     0.000000   
25%      8.000000   4.000000    14.000000   1.000000    0.000000     1.000000   
50%      8.000000   4.000000    34.000000   3.000000    0.000000     1.000000   
75%      9.000000   4.000000    34.000000   4.000000    0.000000     3.500000   
max     10.000000   4.000000    52.000000   9.000000    5.000000     5.000000   

       road_intactness  road_width  road_sign  road_light  road_control  \
count        43.000000   43.000000  43.000000   43.000000     27.000000   
mean          1.232558    1.930233   3.720930    3.302326      5.037037   
std           1.191981    1.386935   0.959305    3.615673      2.710116   
min           0.000000    0.000000   1.000000    1.000000      1.000000   
25%           1.000000    1.000000   3.000000    1.000000      2.000000   
50%           1.000000    2.000000   3.000000    1.000000      7.000000   
75%           1.000000    3.000000   5.000000    5.500000      7.000000   
max           4.000000    5.000000   5.000000   11.000000      7.000000   

         weather  road_surface  road_object  object_distance  didnt_cross  \
count  43.000000     43.000000    43.000000        43.000000    43.000000   
mean    2.139535      3.232558     8.953488         8.697674     8.744186   
std     2.799502      3.038148     0.213083         1.389328     0.726801   
min     1.000000      1.000000     8.000000         2.000000     6.000000   
25%     1.000000      1.000000     9.000000         9.000000     9.000000   
50%     1.000000      1.000000     9.000000         9.000000     9.000000   
75%     1.000000      6.000000     9.000000         9.000000     9.000000   
max     9.000000      9.000000     9.000000         9.000000     9.000000   

       cross_mode  cross_location  cross_direction  road1  road2   km  km_raw  \
count   43.000000       43.000000        43.000000    0.0    0.0  0.0     0.0   
mean     0.186047        0.255814         8.488372    NaN    NaN  NaN     NaN   
std      0.698836        0.847771         1.894504    NaN    NaN  NaN     NaN   
min      0.000000        0.000000         1.000000    NaN    NaN  NaN     NaN   
25%      0.000000        0.000000         9.000000    NaN    NaN  NaN     NaN   
50%      0.000000        0.000000         9.000000    NaN    NaN  NaN     NaN   
75%      0.000000        0.000000 

In [81]:
m_all[m_all['municipal_status'] == 999].shape

(43, 98)

**Null Conclusion:** `municipal_status` == 999 is problematic, spread over numerous years

**Specific values mistmatch investigations:**

In [156]:
temp = m_all[m_all['municipal_status_hebrew'].isnull()==False]

merge_with_hebrew(temp, 'municipal_status')

index_municipal_status   count index_municipal_status_hebrew
0                      0.0  482905                        עירייה
1                     99.0   96533                  מועצה מקומית
2                     20.0    1788                    דרום השרון
3                      9.0    1600                    עמק יזרעאל
4                     25.0    1406                   חבל מודיעין
5                      4.0    1194                       מטה אשר
6                     56.0    1118                          משגב
7                     16.0    1111                       עמק חפר
8                     26.0    1081                     מטה יהודה
9                     19.0    1009                     חוף השרון
10                    33.0     965                     באר טוביה
11                    15.0     916                     חוף הכרמל
12                    18.0     810                      לב השרון
13                     8.0     759                        הגלבוע
14                    13.0     714                         מגידו
15                    14.0     678                          מנשה
16                    40.0     599                       עמק לוד
17                    30.0     585                           גזר
18                    73.0     569                    מטה בנימין
19                     2.0     558                    מרום הגליל
20                    52.0     543                     מעלה יוסף
21                    12.0     520                        זבולון
22                    36.0     461                    חוף אשקלון
23                     6.0     458                     עמק הירדן
24                     1.0     424                  הגליל העליון
25                     3.0     422                  הגליל התחתון
26                    72.0     386                        שומרון
27                     7.0     296                           NaN
28                    27.0     290                       גן רווה
29                    71.0     270                          גולן
30                    55.0     262                 מבואות החרמון
31                    28.0     242                          ברנר
32                    41.0     238                     בני שמעון
33                    50.0     214                          לכיש
34                    38.0     188                         אשכול
35                    34.0     182                          שפיר
36                    35.0     181                          יואב
37                    39.0     153                      שדות נגב
38                    42.0     150                        מרחבים
39                    66.0     146                      שער הנגב
40                    66.0     146                  בוסתן אל-מרג
41                    37.0     146                      שער הנגב
42                    37.0     146                  בוסתן אל-מרג
43                    29.0     143                      חבל יבנה
44                    65.0     135                       אל-בטוף
45                    76.0     127                     גוש עציון
46                    32.0     109                         גדרות
47                    31.0     102                      נחל שורק
48                    51.0      91                           תמר
49                    24.0      80                          אפעל
50                    54.0      70                 הערבה התיכונה
51                    54.0      70                   ערבות הירדן
52                    75.0      70                 הערבה התיכונה
53                    75.0      70                   ערבות הירדן
54                    48.0      65                       רמת נגב
55                    69.0      52                       אל קסום
56                    78.0      46                      הר חברון
57                    45.0      44                         אלונה
58                    53.0      37                     חבל אילות
59                    74.0      31                        מגילות
60                    67.0      26     

In [149]:
temp[temp['municipal_status_hebrew'] == 'בקעת בית שאן']['accident_year'].describe()

count     192.000000
mean     2010.791667
std         1.883612
min      2008.000000
25%      2009.000000
50%      2011.000000
75%      2012.000000
max      2014.000000
Name: accident_year, dtype: float64

In [150]:
temp[temp['municipal_status_hebrew'] == 'עמק המעיינות']['accident_year'].describe()

count     104.000000
mean     2016.394231
std         1.161003
min      2015.000000
25%      2015.000000
50%      2016.500000
75%      2017.000000
max      2018.000000
Name: accident_year, dtype: float64

**Specific values conclusion:**

`municipal_status` 7 was called `בקעת בית שאן` until and including 2014, and `עמק המעיינות` since

## yishuv_shape and yishuv_shape_hebrew

In [82]:
# yishuv_shape                                 605597 non-null float64
# yishuv_shape_hebrew                          561532 non-null object
m_all[(m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)].shape

(44065, 98)

In [83]:
m_all[(m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  4.406500e+04     4.406500e+04   44065.000000       3851.000000   
mean   2.012812e+09     1.201508e+10       1.000227          1.032719   
std    3.231172e+06     2.130201e+08       0.021303          0.253740   
min    2.008000e+09     1.200800e+10       1.000000          1.000000   
25%    2.010027e+09     1.201003e+10       1.000000          1.000000   
50%    2.013005e+09     1.201300e+10       1.000000          1.000000   
75%    2.016012e+09     1.201601e+10       1.000000          1.000000   
max    2.018100e+09     3.201003e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy     road_type  \
count   44065.000000       44065.000000       44065.000000  44065.000000   
mean        4.076138           2.780279           1.256008      3.665381   
std         3.130061           0.510036           1.042107      0.472247   
min         1.000000           1.000000           1.000000      1.000000   
25%         2.000000           3.000000           1.000000      3.000000   
50%         3.000000           3.000000           1.000000      4.000000   
75%         5.000000           3.000000           1.000000      4.000000   
max        20.000000           3.000000           9.000000      4.000000   

         road_shape      day_type   police_unit      one_lane    multi_lane  \
count  44065.000000  44065.000000  44065.000000  44065.000000  44065.000000   
mean       8.220175      3.868512     29.426620      1.854851      1.139362   
std        0.997726      0.532021     17.330462      2.570615      1.326877   
min        1.000000      1.000000     11.000000      0.000000      0.000000   
25%        8.000000      4.000000     12.000000      0.000000      0.000000   
50%        8.000000      4.000000     20.000000      1.000000      0.000000   
75%        9.000000      4.000000     51.000000      3.000000      2.000000   
max       11.000000      4.000000     61.000000      9.000000      5.000000   

        speed_limit  road_intactness    road_width     road_sign  \
count  44065.000000     44065.000000  44065.000000  44065.000000   
mean       3.586066         0.811733      2.826733      3.236809   
std        1.685675         0.463543      1.323100      0.713400   
min        0.000000         0.000000      0.000000      1.000000   
25%        3.000000         1.000000      2.000000      3.000000   
50%        4.000000         1.000000      3.000000      3.000000   
75%        5.000000         1.000000      4.000000      3.000000   
max        8.000000         4.000000      5.000000      5.000000   

         road_light  road_control       weather  road_surface   road_object  \
count  44065.000000  19199.000000  44065.000000  44065.000000  44065.000000   
mean       2.798003      3.639617      1.752275      1.734551      8.594599   
std        2.713568      2.238065      2.223559      2.192272      1.309373   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      2.000000      1.000000      1.000000      9.000000   
50%        1.000000      2.000000      1.000000      1.000000      9.000000   
75%        3.000000      6.000000      1.000000      1.000000      9.000000   
max       11.000000      7.000000      9.000000      9.000000      9.000000   

       object_distance   didnt_cross    cross_mode  cross_location  \
count     44065.000000  44065.000000  44065.000000    44065.000000   
mean          8.308363      8.970975      0.061046        0.061682   
std           2.107291      0.360163      0.493692        0.475917   
min           1.000000      1.000000      0.000000        0.000000   
25%           9.000000      9.000000      0.000000        0.000000   
50%           9.000000      9.000000      0.000000        0.000000   
75%           9.000000      9.000000      0.000000        0.000000   
max           9.000000      9.000000      9.000000        9.000000   

      

In [84]:
m_all[(m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)]['yishuv_shape'].value_counts()

99.0    44059
53.0        6
Name: yishuv_shape, dtype: int64

In [85]:
m_all[m_all['yishuv_shape']==99].shape

(44059, 98)

In [88]:
m_all[(m_all['yishuv_shape']==99) & (m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)]['accident_year'].value_counts()

2009    4765
2008    4602
2010    4348
2011    4072
2017    3932
2018    3851
2013    3829
2012    3751
2015    3716
2016    3654
2014    3539
Name: accident_year, dtype: int64

In [87]:
m_all[m_all['yishuv_shape']==53].shape

(30, 98)

In [89]:
m_all[(m_all['yishuv_shape']==53) & (m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == True)]['accident_year'].value_counts()

2010    2
2009    2
2008    2
Name: accident_year, dtype: int64

In [90]:
m_all[m_all['yishuv_shape']==53]['accident_year'].value_counts()

2017    9
2015    6
2018    6
2016    3
2010    2
2009    2
2008    2
Name: accident_year, dtype: int64

**Null Conclusion:** `yishuv_shape` translation issues:
- 99 spread over numerous years
- 53 for years 2008-2010, rest of the years there is 53 without problems

**Specific values mistmatch investigations:**

In [157]:
temp = m_all[(m_all['yishuv_shape'].isnull() == False) & (m_all['yishuv_shape_hebrew'].isnull() == False)]
temp.shape

(561532, 98)

In [158]:
merge_with_hebrew(temp, 'yishuv_shape')

index_yishuv_shape   count              index_yishuv_shape_hebrew
0                 13.0  107817                                    NaN
1                 14.0  105335                                    NaN
2                 16.0   79804                                    NaN
3                 12.0   64657                                    NaN
4                 15.0   56415                                    NaN
5                 11.0   25217                                ירושלים
6                 26.0   21513                                    NaN
7                 27.0   18525                                    NaN
8                 17.0   12449                                    NaN
9                 28.0   11180                                    NaN
10                31.0   10534                                    NaN
11                10.0    9452                            ראשון לציון
12                25.0    9073                                    NaN
13                 9.0    6789                                    NaN
14                33.0    6680                                קיבוצים
15                18.0    6522                                    NaN
16                35.0    1701                                    NaN
17                19.0    1608       יישובים יהודיים 4999-2000 תושבים
18                37.0    1417                       יישובים קהילתיים
19                29.0    1238                                    NaN
20                32.0    1077                        מושבים שיתופיים
21                45.0     745                                    NaN
22                52.0     675                                    NaN
23                49.0     635                                    NaN
24                34.0     357                                    NaN
25                46.0      66                            שבטי בדווים
26                51.0      27                                   מקום
27                53.0      24                         סמלים קיבוציים
28                 NaN   87474   יישובים יהודיים 499999-200000 תושבים
29                 NaN   62273      100,000-199,999-תושב, יישוב יהודי
30                 NaN   43062   יישובים יהודיים 199999-100000 תושבים
31                 NaN   40294                            תל אביב-יפו
32                 NaN   40190        20,000-49,999-תושב, יישוב יהודי
33                 NaN   39614     יישובים יהודיים 49999-20000 תושבים
34                 NaN   31926     יישובים יהודיים 99999-50000 תושבים
35                 NaN   24489        50,000-99,999-תושב, יישוב יהודי
36                 NaN   24363    יישובים יהודיים 500000 תושבים ומעלה
37                 NaN   20343                                   חיפה
38                 NaN   12579  יישובים לא יהודיים 49999-20000 תושבים
39                 NaN    9817     10,000-19,999-תושב, יישוב לא-יהודי
40                 NaN    8934     20,000-49,999-תושב, יישוב לא-יהודי
41                 NaN    8708  יישובים לא יהודיים 19999-10000 תושבים
42                 NaN    7385        10,000-19,999-תושב, יישוב יהודי
43                 NaN    6788                                  אשדוד
44                 NaN    5974    יישובים לא יהודיים 9999-5000 תושבים
45                 NaN    5821          מושבים - לרבות כפרים שיתופיים
46                 NaN    5206       2,000-9,999-תושב, יישוב לא-יהודי
47                 NaN    5203  יישובים לא יהודיים 99999-50000 תושבים
48                 NaN    5064     יישובים יהודיים 19999-10000 תושבים
49                 NaN    4713          מושבים (לרבות כפרים שיתופיים)
50                 NaN    4059          2,000-9,999-תושב, יישוב יהודי
51                 NaN    3870     50,000-99,999-תושב, יישוב לא-יהודי
52                 NaN    2463       יישובים יהודיים 9999-5000 תושבים
53                 NaN    1167    יישובים לא יהודיים 4999-2000 תושבים
54                 NaN     882          יישובים כפריים אחרים, יהודיים
55                 NaN     819           יישובים כפריים אחרים יהודיים
56            

In [159]:
calc_diff_counts_hebrew(temp, 'yishuv_shape')

Shape of data: (561532, 98)


0     20343.0
1     43062.0
2     36742.0
3     24363.0
4     16225.0
5    -14397.0
6    -10413.0
7     -6692.0
8    -12040.0
9    -13183.0
10    -9809.0
11    -3127.0
12     -744.0
13    -2663.0
14    -2254.0
15    -2186.0
16    -5684.0
17    -5180.0
18    -5263.0
19    -4736.0
20    -4744.0
21    -4461.0
22    -4528.0
23    -4429.0
24    -4356.0
25    -3993.0
26    -3843.0
27    -2439.0
28        NaN
29        NaN
30        NaN
31        NaN
32        NaN
33        NaN
34        NaN
35        NaN
36        NaN
37        NaN
38        NaN
39        NaN
40        NaN
41        NaN
42        NaN
43        NaN
44        NaN
45        NaN
46        NaN
dtype: float64

**Specific values conclusion:** a big mess, worth investing more time to understand

### street1 and street1_hebrew

In [91]:
# street1                                      553240 non-null float64
# street1_hebrew                               389936 non-null object
m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)].shape

(163304, 98)

In [92]:
m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  1.633040e+05     1.633040e+05  163304.000000      11643.000000   
mean   2.012696e+09     3.065780e+10       2.864510          2.876492   
std    3.209588e+06     5.026161e+09       0.502617          0.481437   
min    2.008000e+09     1.200800e+10       1.000000          1.000000   
25%    2.010013e+09     3.200905e+10       3.000000          3.000000   
50%    2.013011e+09     3.201205e+10       3.000000          3.000000   
75%    2.015091e+09     3.201507e+10       3.000000          3.000000   
max    2.018100e+09     3.201810e+10       3.000000          3.000000   

       accident_type  accident_severity  location_accuracy      road_type  \
count  163304.000000      163304.000000      163304.000000  163304.000000   
mean        4.938415           2.985359           2.026307       1.993191   
std         4.201458           0.130662           0.427273       0.082238   
min         1.000000           1.000000           1.000000       1.000000   
25%         3.000000           3.000000           2.000000       2.000000   
50%         3.000000           3.000000           2.000000       2.000000   
75%         8.000000           3.000000           2.000000       2.000000   
max        20.000000           3.000000           9.000000       2.000000   

          road_shape       day_type    police_unit       one_lane  \
count  163304.000000  163304.000000  163304.000000  163304.000000   
mean        8.682139       3.876696      25.736351       8.597922   
std         0.523821       0.514436      16.734344       1.646050   
min         1.000000       1.000000      11.000000       0.000000   
25%         8.000000       4.000000      12.000000       9.000000   
50%         9.000000       4.000000      14.000000       9.000000   
75%         9.000000       4.000000      38.000000       9.000000   
max        11.000000       4.000000      61.000000       9.000000   

          multi_lane    speed_limit  road_intactness     road_width  \
count  163304.000000  163304.000000    163304.000000  163304.000000   
mean        0.035835       0.083048         0.057004       0.140989   
std         0.326048       0.415699         0.268631       0.615550   
min         0.000000       0.000000         0.000000       0.000000   
25%         0.000000       0.000000         0.000000       0.000000   
50%         0.000000       0.000000         0.000000       0.000000   
75%         0.000000       0.000000         0.000000       0.000000   
max         5.000000       7.000000         4.000000       5.000000   

           road_sign     road_light  road_control        weather  \
count  163304.000000  163304.000000   2629.000000  163304.000000   
mean        4.885765       9.291744      5.384557       8.530269   
std         0.493530       2.805098      1.985700       1.874383   
min         1.000000       1.000000      1.000000       1.000000   
25%         5.000000       6.000000      5.000000       9.000000   
50%         5.000000      11.000000      6.000000       9.000000   
75%         5.000000      11.000000      7.000000       9.000000   
max         5.000000      11.000000      7.000000       9.000000   

        road_surface    road_object  object_distance    didnt_cross  \
count  163304.000000  163304.000000    163304.000000  163304.000000   
mean        8.541138       8.838277         8.969560       8.966553   
std         1.846632       0.923896        12.496107       0.381145   
min         1.000000       1.000000         1.000000       0.000000   
25%         9.000000       9.000000         9.000000       9.000000   
50%         9.000000       9.000000         9.000000       9.000000   
75%         9.000000       9.000000         9.000000       9.000000   
max         9.000000       9.000000      1462.000000       9.000000   

          cross_mode  cross_location  cross_direction  road1  road2   km  \
count  163304.000000   163304.000000    163304.000000    0.0    0.0  0.0  

In [163]:
m_all['street1'].nunique()

3331

In [94]:
m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)]['street1'].value_counts()

0.0       160902
9998.0       831
9991.0       825
9992.0       246
9993.0       188
9994.0       131
942.0         21
9995.0        16
999.0         13
6713.0         8
916.0          6
195.0          6
547.0          4
805.0          4
7001.0         3
9999.0         3
202.0          3
221.0          2
828.0          2
6712.0         2
921.0          2
687.0          2
781.0          2
261.0          2
130.0          2
6742.0         2
5094.0         2
6718.0         1
9291.0         1
105.0          1
6721.0         1
6724.0         1
6725.0         1
6731.0         1
6732.0         1
914.0          1
4.0            1
574.0          1
4098.0         1
193.0          1
1058.0         1
139.0          1
197.0          1
102.0          1
198.0          1
794.0          1
812.0          1
1104.0         1
6505.0         1
6506.0         1
6519.0         1
6520.0         1
6521.0         1
280.0          1
6746.0         1
206.0          1
9099.0         1
6743.0         1
2040.0        

In [97]:
m_all[(m_all['street1'] != 0) & (m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)].shape

(2402, 98)

In [108]:
num_total = []
for street in m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)]['street1'].value_counts().index:
    num_total.append(m_all[m_all['street1'] == street].shape[0])
num_total - m_all[(m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)]['street1'].value_counts()

0.0          0
9998.0       0
9991.0     102
9992.0       0
9993.0       0
9994.0       0
942.0      486
9995.0       0
999.0       42
6713.0       2
916.0      510
195.0     3577
547.0      506
805.0       96
7001.0     517
9999.0       0
202.0     1144
221.0     1591
828.0       65
6712.0       4
921.0      286
687.0       10
781.0       34
261.0      160
130.0      398
6742.0      14
5094.0       0
6718.0       0
9291.0       0
105.0     1472
6721.0      28
6724.0       4
6725.0      70
6731.0      19
6732.0       1
914.0      416
4.0          0
574.0       42
4098.0       2
193.0      131
1058.0      70
139.0      802
197.0      333
102.0     2034
198.0      193
794.0       65
812.0       82
1104.0     301
6505.0     117
6506.0     127
6519.0      51
6520.0      69
6521.0      90
280.0      116
6746.0       1
206.0      597
9099.0       0
6743.0       1
2040.0       0
1177.0       9
7678.0       0
164.0      462
5394.0      10
235.0      708
236.0      235
691.0       42
1898.0    

In [164]:
temp = m_all[(m_all['street1'].isnull()==False) & (m_all['street1_hebrew'].isnull()==False)]
temp.shape

(389936, 98)

In [167]:
m_all[(m_all['street1'] != 0) & (m_all['street1'].isnull() == False) & (m_all['street1_hebrew'].isnull() == True)]['street1'].value_counts()

9998.0    831
9991.0    825
9992.0    246
9993.0    188
9994.0    131
942.0      21
9995.0     16
999.0      13
6713.0      8
916.0       6
195.0       6
805.0       4
547.0       4
9999.0      3
7001.0      3
202.0       3
130.0       2
6742.0      2
5094.0      2
687.0       2
6712.0      2
221.0       2
781.0       2
921.0       2
261.0       2
828.0       2
461.0       1
154.0       1
6506.0      1
6743.0      1
108.0       1
2678.0      1
6505.0      1
4.0         1
198.0       1
101.0       1
206.0       1
123.0       1
102.0       1
6521.0      1
6520.0      1
161.0       1
361.0       1
950.0       1
6721.0      1
6725.0      1
4098.0      1
893.0       1
658.0       1
925.0       1
1058.0      1
1430.0      1
235.0       1
794.0       1
701.0       1
6731.0      1
149.0       1
2040.0      1
1233.0      1
7756.0      1
975.0       1
6519.0      1
671.0       1
107.0       1
163.0       1
103.0       1
105.0       1
2372.0      1
1179.0      1
6746.0      1
9099.0      1
2572.0

**Null Conclusion:** 160902 out of 163304 that are missing are `street1` == 0, other 2402 miscellenious.  
Some of the miscellenious all the index translation is missing, some only part of the instances translation missing.
See details above.

**Specific values mistmatch investigations:**

Didn't do detailed investigation, especially due to all the differences already in the nulls

**Specific values conclusion:**

See above

## street2 and street2_hebrew

In [109]:
# street2                                      71838 non-null float64
# street2_hebrew                               70713 non-null object
m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)].shape

(1125, 98)

In [111]:
m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)]['street2'].value_counts()

0.0       1092
9998.0      15
9991.0       7
9992.0       3
9994.0       2
828.0        1
3226.0       1
130.0        1
9993.0       1
2632.0       1
4.0          1
Name: street2, dtype: int64

In [112]:
num_total = []
for street in m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)]['street2'].value_counts().index:
    num_total.append(m_all[m_all['street2'] == street].shape[0])
num_total - m_all[(m_all['street2'].isnull() == False) & (m_all['street2_hebrew'].isnull() == True)]['street2'].value_counts()

0.0        0
9998.0     1
9991.0    27
9992.0     0
9994.0     0
828.0      7
3226.0     0
130.0     76
9993.0     1
2632.0    22
4.0        0
Name: street2, dtype: int64

**Null Conclusion:** 1092 out of 1125 that are missing are `street2` == 0, other 33 miscellenious.  
Some of the miscellenious all the index translation is missing, some only part of the instances translation missing.
See details above.

**Specific values mistmatch investigations:** see conclusions for `street1` above

**Specific values conclusion:** see conclusions for `street1` above

## non_urban_intersection and non_urban_intersection_hebrew

In [115]:
# non_urban_intersection                       34382 non-null float64
# non_urban_intersection_hebrew                33018 non-null object
m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)].shape

(1364, 98)

In [168]:
m_all['non_urban_intersection'].nunique()

1798

In [116]:
m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  1.364000e+03     1.364000e+03    1364.000000               0.0   
mean   2.014349e+09     2.230760e+10       2.029326               NaN   
std    1.909412e+06     9.998990e+09       0.999937               NaN   
min    2.008000e+09     1.200800e+10       1.000000               NaN   
25%    2.015013e+09     1.201505e+10       1.000000               NaN   
50%    2.015041e+09     3.200805e+10       3.000000               NaN   
75%    2.015072e+09     3.201504e+10       3.000000               NaN   
max    2.017075e+09     3.201708e+10       3.000000               NaN   

       accident_type  accident_severity  location_accuracy  road_type  \
count    1364.000000        1364.000000        1364.000000     1364.0   
mean        3.648827           2.925953           1.029326        3.0   
std         3.129017           0.317641           0.404330        0.0   
min         1.000000           1.000000           1.000000        3.0   
25%         2.000000           3.000000           1.000000        3.0   
50%         3.000000           3.000000           1.000000        3.0   
75%         3.000000           3.000000           1.000000        3.0   
max        19.000000           3.000000           9.000000        3.0   

        road_shape     day_type  police_unit     one_lane   multi_lane  \
count  1364.000000  1364.000000  1364.000000  1364.000000  1364.000000   
mean      8.572581     3.893695    31.214809     5.109238     0.834311   
std       0.805254     0.471947    17.584970     4.183144     1.274663   
min       1.000000     1.000000    11.000000     0.000000     0.000000   
25%       8.000000     4.000000    12.000000     0.000000     0.000000   
50%       9.000000     4.000000    34.000000     9.000000     0.000000   
75%       9.000000     4.000000    51.000000     9.000000     2.000000   
max       9.000000     4.000000    61.000000     9.000000     5.000000   

       speed_limit  road_intactness   road_width    road_sign   road_light  \
count  1364.000000      1364.000000  1364.000000  1364.000000  1364.000000   
mean      1.802053         0.456012     1.530059     4.054252     6.046921   
std       2.127029         0.512758     1.766188     1.015646     4.231992   
min       0.000000         0.000000     0.000000     1.000000     1.000000   
25%       0.000000         0.000000     0.000000     3.000000     1.000000   
50%       0.000000         0.000000     0.000000     5.000000     6.000000   
75%       4.000000         1.000000     3.000000     5.000000    11.000000   
max       7.000000         3.000000     5.000000     5.000000    11.000000   

       road_control      weather  road_surface  road_object  object_distance  \
count    644.000000  1364.000000   1364.000000  1364.000000       1364.00000   
mean       2.785714     5.260264      5.247067     8.849707          8.79912   
std        1.759413     3.958201      3.961826     0.866000          1.17474   
min        1.000000     1.000000      1.000000     2.000000          1.00000   
25%        2.000000     1.000000      1.000000     9.000000          9.00000   
50%        2.000000     9.000000      9.000000     9.000000          9.00000   
75%        2.000000     9.000000      9.000000     9.000000          9.00000   
max        7.000000     9.000000      9.000000     9.000000          9.00000   

       didnt_cross   cross_mode  cross_location  cross_direction        road1  \
count  1364.000000  1364.000000     1364.000000      1364.000000  1363.000000   
mean      8.990469     0.071848        0.062317         8.840176   349.512106   
std       0.196962     0.539666        0.456230         1.087229  1084.261136   
min       3.000000     0.000000        0.000000         1.000000     1.000000   
25%       9.000000     0.000000        0.000000         9.000000     6.000000   
50%       9.000000     0.000000        0.000000         9.000000    60.000000   
75%       9.000000     0.000000        0.00

In [117]:
m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)]['non_urban_intersection'].value_counts()

1203.0      63
8015.0      31
867.0       24
57.0        24
2043.0      20
5.0         20
4071.0      19
317.0       15
58.0        15
325.0       14
2324.0      13
3497.0      12
4135.0      12
8017.0      11
4037.0      10
319.0       10
373.0       10
153.0        9
9378.0       9
4049.0       9
1083.0       9
4083.0       9
9736.0       9
1983.0       9
4197.0       9
475.0        8
641.0        8
1191.0       8
335.0        8
347.0        7
8055.0       7
1265.0       7
2169.0       7
1301.0       7
4043.0       7
639.0        7
4194.0       7
4182.0       7
8056.0       7
9470.0       6
4158.0       6
521.0        6
105.0        6
4189.0       6
3017.0       6
1137.0       6
3019.0       6
755.0        6
3898.0       6
1131.0       6
4223.0       6
361.0        6
831.0        5
4112.0       5
7095.0       5
536.0        5
683.0        5
863.0        5
3478.0       5
431.0        5
1421.0       5
8026.0       5
693.0        5
1161.0       5
4200.0       5
1317.0       5
1339.0    

In [118]:
num_total = []
for inter in m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)]['non_urban_intersection'].value_counts().index:
    num_total.append(m_all[m_all['non_urban_intersection'] == inter].shape[0])
num_total - m_all[(m_all['non_urban_intersection'].isnull() == False) & (m_all['non_urban_intersection_hebrew'].isnull() == True)]['non_urban_intersection'].value_counts()

1203.0      202
8015.0        8
867.0       254
57.0        770
2043.0      210
5.0         340
4071.0      172
317.0       252
58.0        243
325.0       103
2324.0       16
3497.0       31
4135.0       71
8017.0      221
4037.0       50
319.0        98
373.0       109
153.0        85
9378.0       40
4049.0      115
1083.0       90
4083.0       26
9736.0       32
1983.0       79
4197.0       49
475.0        27
641.0        37
1191.0       57
335.0       137
347.0        45
8055.0       84
1265.0       19
2169.0       33
1301.0       87
4043.0       41
639.0        83
4194.0       60
4182.0        6
8056.0       78
9470.0       26
4158.0       48
521.0        62
105.0        85
4189.0       43
3017.0       32
1137.0       30
3019.0       46
755.0        24
3898.0       15
1131.0       28
4223.0       42
361.0        60
831.0        89
4112.0       16
7095.0        9
536.0        15
683.0        53
863.0        32
3478.0       38
431.0        33
1421.0       17
8026.0       60
693.0   

**Null Conclusion:** A lot of `non_urban_intersection` are missing, most of them only part of the instances translation missing. See details above.

**Specific values mistmatch investigations:** because of all the issues above, is it worth to investigate?

**Specific values conclusion:** because of all the issues above, not investigated

## accident_hour_raw and accident_hour_raw_hebrew

In [119]:
# accident_hour_raw                            720541 non-null int64
# accident_hour_raw_hebrew                     322739 non-null object
m_all[(m_all['accident_hour_raw'].isnull() == False) & (m_all['accident_hour_raw_hebrew'].isnull() == True)].shape

(397802, 98)

In [120]:
m_all[(m_all['accident_hour_raw'].isnull() == False) & (m_all['accident_hour_raw_hebrew'].isnull() == True)].describe()

id  provider_and_id  provider_code  file_type_police  \
count  3.978020e+05     3.978020e+05  397802.000000               0.0   
mean   2.010373e+09     2.787766e+10       2.586729               NaN   
std    1.699263e+06     8.097839e+09       0.809784               NaN   
min    2.008005e+09     1.200800e+10       1.000000               NaN   
25%    2.009029e+09     3.200803e+10       3.000000               NaN   
50%    2.010055e+09     3.200908e+10       3.000000               NaN   
75%    2.012022e+09     3.201106e+10       3.000000               NaN   
max    2.013062e+09     3.201306e+10       3.000000               NaN   

       accident_type  accident_severity  location_accuracy      road_type  \
count  397802.000000      397802.000000      397802.000000  397802.000000   
mean        4.660394           2.972235           2.573632       2.292776   
std         4.070695           0.186378           1.864900       0.856325   
min         1.000000           1.000000           1.000000       1.000000   
25%         2.000000           3.000000           1.000000       2.000000   
50%         3.000000           3.000000           2.000000       2.000000   
75%         5.000000           3.000000           3.000000       2.000000   
max        20.000000           3.000000           9.000000       4.000000   

          road_shape       day_type    police_unit       one_lane  \
count  397802.000000  397802.000000  397802.000000  397802.000000   
mean        8.453693       3.899493      30.892253       7.583471   
std         0.599281       0.460079      17.877736       3.046661   
min         0.000000       1.000000      11.000000       0.000000   
25%         8.000000       4.000000      14.000000       9.000000   
50%         8.000000       4.000000      20.000000       9.000000   
75%         9.000000       4.000000      51.000000       9.000000   
max        15.000000       4.000000      61.000000       9.000000   

          multi_lane    speed_limit  road_intactness     road_width  \
count  397802.000000  397802.000000    397802.000000  397802.000000   
mean        0.222025       0.361258         0.154625       0.480646   
std         0.761762       0.989774         0.380194       1.111834   
min         0.000000       0.000000         0.000000       0.000000   
25%         0.000000       0.000000         0.000000       0.000000   
50%         0.000000       0.000000         0.000000       0.000000   
75%         0.000000       0.000000         0.000000       0.000000   
max         5.000000       7.000000         4.000000       5.000000   

           road_sign     road_light  road_control        weather  \
count  397802.000000  397802.000000  39412.000000  397802.000000   
mean        4.635776       8.409709      3.745331       7.514138   
std         0.803033       3.727153      2.303807       3.097870   
min         1.000000       1.000000      0.000000       1.000000   
25%         5.000000       6.000000      2.000000       9.000000   
50%         5.000000      11.000000      2.000000       9.000000   
75%         5.000000      11.000000      6.000000       9.000000   
max         5.000000      11.000000      7.000000       9.000000   

        road_surface    road_object  object_distance    didnt_cross  \
count  397802.000000  397802.000000    397802.000000  397802.000000   
mean        7.519233       8.892457         8.954774       8.960629   
std         3.091166       0.749012        11.090615       0.402947   
min         1.000000       1.000000         1.000000       1.000000   
25%         9.000000       9.000000         9.000000       9.000000   
50%         9.000000       9.000000         9.000000       9.000000   
75%         9.000000       9.000000         9.000000       9.000000   
max         9.000000       9.000000      1462.000000       9.000000   

          cross_mode  cross_location  cross_direction         road1  \
count  397802.000000   397802.000000    397802.000000  85412.000000   
mean    

In [121]:
m_all[(m_all['accident_hour_raw'].isnull() == False) & (m_all['accident_hour_raw_hebrew'].isnull() == True)]['accident_hour_raw'].value_counts()

65    12903
33    12269
69    12125
57    11918
49    11206
73    10993
53    10980
61    10787
67    10518
63    10179
55     9835
35     9660
71     9616
45     9526
31     9172
59     9114
51     8968
41     8902
37     8778
77     8219
75     8005
47     7733
32     7401
43     7381
39     7350
81     6702
79     6071
34     5498
83     5252
85     5242
29     5182
66     4800
70     4340
89     4192
64     4145
68     4114
30     4107
62     4042
36     4036
54     4011
87     3988
58     3770
72     3669
74     3571
56     3533
52     3405
50     3365
93     3271
38     3249
60     3217
27     3109
91     3050
48     3018
46     2918
42     2918
76     2764
78     2735
95     2687
40     2634
44     2504
28     2458
82     2240
80     2180
25     1836
84     1630
86     1614
96     1467
26     1287
90     1233
88     1193
94     1061
92      956
Name: accident_hour_raw, dtype: int64

**Null Conclusion:** Half the values of missing, a lot of different views. See details above

**Specific values mistmatch investigations:** not investigated because of all the issues above

**Specific values conclusion:** not investigated because of all the issues above